const fs = require('fs');
const content = [
"import { useState } from \"react\";",
"import { Link, useLocation } from \"react-router\";",
"import { useTranslation } from \"react-i18next\";",
"import { useAuth } from \"@/hooks/useAuth\";",
"import { trpc } from \"@/providers/trpc\";",
"import { Button } from \"@/components/ui/button\";",
"import { Sheet, SheetContent, SheetTrigger, SheetTitle } from \"@/components/ui/sheet\";",
"import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from \"@/components/ui/dropdown-menu\";",
"import { Avatar, AvatarFallback, AvatarImage } from \"@/components/ui/avatar\";",
"import { ShoppingCart, Menu, Globe, LogOut, Shield, Package, User } from \"lucide-react\";",
"",
"export default function Navbar() {",
"  const { t, i18n } = useTranslation();",
"  const location = useLocation();",
"  const { user, isAuthenticated, logout } = useAuth();",
"  const [open, setOpen] = useState(false);",
"  const [langOpen, setLangOpen] = useState(false);",
"  const isActive = (path: string) => location.pathname === path;",
"  const changeLanguage = (lang: string) => { i18n.changeLanguage(lang); setLangOpen(false); setOpen(false); };",
"  const languages = [",
"    { code: \"en\", label: \"English\" }, { code: \"ja\", label: \"日本語\" }, { code: \"es\", label: \"Español\" },",
"    { code: \"fr\", label: \"Français\" }, { code: \"de\", label: \"Deutsch\" }, { code: \"zh\", label: \"中文\" }, { code: \"ko\", label: \"한국어\" },",
"  ];",
"",
"  return (",
"    <nav className=\"sticky top-0 z-50 bg-background/80 backdrop-blur-md border-b border-border\">",
"      <div className=\"container px-4 md:px-6 mx-auto\">",
"        <div className=\"flex items-center justify-between h-16\">",
"          <Link to=\"/\" className=\"flex items-center gap-2 shrink-0\">",
"            <div className=\"w-8 h-8 rounded-full bg-gradient-to-br from-amber-400 to-amber-600 flex items-center justify-center text-black font-bold text-sm\">ラ</div>",
"            <span className=\"font-bold text-lg hidden sm:block text-foreground\">{t(\"nav.brand\")}</span>",
"          </Link>",
"          <div className=\"hidden md:flex items-center gap-6\">",
"            <Link to=\"/shop\" className={`text-sm font-medium transition-colors ${isActive(\"/shop\") ? \"text-primary\" : \"text-muted-foreground hover:text-foreground\"}`}>{t(\"nav.shop\")}</Link>",
"            <Link to=\"/social\" className={`text-sm font-medium transition-colors ${isActive(\"/social\") ? \"text-primary\" : \"text-muted-foreground hover:text-foreground\"}`}>{t(\"nav.forum\")}</Link>",
"            <Link to=\"/marketplace\" className={`text-sm font-medium transition-colors ${isActive(\"/marketplace\") ? \"text-primary\" : \"text-muted-foreground hover:text-foreground\"}`}>{t(\"nav.marketplace\")}</Link>",
"            <Link to=\"/donate\" className={`text-sm font-medium transition-colors ${isActive(\"/donate\") ? \"text-primary\" : \"text-muted-foreground hover:text-foreground\"}`}>{t(\"nav.donate\")}</Link>",
"            {!isAuthenticated && <Link to=\"/login\" className={`text-sm font-medium transition-colors ${isActive(\"/login\") ? \"text-primary\" : \"text-muted-foreground hover:text-foreground\"}`}>{t(\"nav.login\")}</Link>}",
"            {isAuthenticated && <span className=\"text-sm font-medium text-muted-foreground\">@{user?.username}</span>}",
"          </div>",
"          <div className=\"flex items-center gap-2\">",
"            <Link to=\"/shop\"><Button variant=\"ghost\" size=\"icon\" className=\"text-foreground hover:text-primary\"><ShoppingCart className=\"h-5 w-5\" /></Button></Link>",
"            <Sheet open={langOpen} onOpenChange={setLangOpen}>",
"              <SheetTrigger asChild><Button variant=\"ghost\" size=\"icon\" className=\"text-foreground hover:text-primary\"><Globe className=\"h-5 w-5\" /></Button></SheetTrigger>",
"              <SheetContent side=\"right\" className=\"bg-background border-border\"><SheetTitle className=\"text-foreground\">{t(\"nav.language\")}</SheetTitle><div className=\"mt-4 space-y-2\">{languages.map((l) => (<button key={l.code} onClick={() => changeLanguage(l.code)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-colors ${i18n.language === l.code ? \"bg-primary/10 text-primary\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{l.label}</button>))}</div></SheetContent>",
"            </Sheet>",
"            {isAuthenticated && user && (",
"              <div className=\"hidden md:flex items-center gap-2\">",
"                <DropdownMenu>",
"                  <DropdownMenuTrigger asChild>",
"                    <Avatar className=\"h-8 w-8 border border-primary/30 cursor-pointer hover:border-primary transition-colors\">",
"                      <AvatarImage src={user.avatar ?? undefined} /><AvatarFallback className=\"bg-primary/20 text-primary text-xs\">{user.name?.charAt(0) ?? \"U\"}</AvatarFallback>",
"                    </Avatar>",
"                  </DropdownMenuTrigger>",
"                  <DropdownMenuContent align=\"end\" className=\"w-48 bg-background border-border\">",
"                    <div className=\"px-3 py-2 border-b border-border\"><p className=\"text-sm font-medium text-foreground\">{user.name ?? user.username}</p><p className=\"text-xs text-muted-foreground\">@{user.username}</p></div>",
"                    <DropdownMenuItem asChild className=\"cursor-pointer\"><Link to={`/profile/${user.id}`} className=\"flex items-center gap-2 text-foreground\"><User className=\"h-4 w-4\" /> My Profile</Link></DropdownMenuItem>",
"                    {user.role === \"admin\" && <DropdownMenuItem asChild className=\"cursor-pointer\"><Link to=\"/admin\" className=\"flex items-center gap-2 text-primary\"><Shield className=\"h-4 w-4\" /> Admin Dashboard</Link></DropdownMenuItem>}",
"                    <DropdownMenuSeparator className=\"bg-border\" />",
"                    <DropdownMenuItem onClick={logout} className=\"cursor-pointer text-destructive focus:text-destructive\"><LogOut className=\"h-4 w-4 mr-2\" /> Logout</DropdownMenuItem>",
"                  </DropdownMenuContent>",
"                </DropdownMenu>",
"              </div>",
"            )}",
"            <Sheet open={open} onOpenChange={setOpen}>",
"              <SheetTrigger asChild><Button variant=\"ghost\" size=\"icon\" className=\"md:hidden text-foreground\"><Menu className=\"h-5 w-5\" /></Button></SheetTrigger>",
"              <SheetContent side=\"right\" className=\"bg-background border-border w-[280px]\">",
"                <SheetTitle className=\"text-foreground mb-4\">{t(\"nav.menu\")}</SheetTitle>",
"                <div className=\"flex flex-col gap-1 mt-4\">",
"                  <Link to=\"/\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{t(\"nav.home\")}</Link>",
"                  <Link to=\"/shop\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/shop\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{t(\"nav.shop\")}</Link>",
"                  <Link to=\"/social\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/social\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{t(\"nav.forum\")}</Link>",
"                  <Link to=\"/marketplace\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/marketplace\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{t(\"nav.marketplace\")}</Link>",
"                  <Link to=\"/donate\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/donate\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}>{t(\"nav.donate\")}</Link>",
"                  {isAuthenticated && <Link to={`/profile/${user?.id}`} onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(`/profile/${user?.id}`) ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}><User className=\"h-4 w-4\" /> My Profile</Link>}",
"                  {isAuthenticated && user?.role === \"admin\" && <Link to=\"/admin\" onClick={() => setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium ${isActive(\"/admin\") ? \"text-primary bg-primary/10\" : \"text-muted-foreground hover:text-foreground hover:bg-muted\"}`}><Shield className=\"h-4 w-4\" />Admin</Link>}",
"                  {!isAuthenticated && <Link to=\"/login\" onClick={() => setOpen(false)} className=\"flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium text-primary bg-primary/10\">{t(\"nav.login\")}</Link>}",
"                  {isAuthenticated && <button onClick={() => { logout(); setOpen(false); }} className=\"flex items-center gap-3 px-3 py-3 rounded-lg text-sm font-medium text-destructive hover:bg-destructive/10 mt-2\"><LogOut className=\"h-4 w-4\" />{t(\"nav.logout\")}</button>}",
"                </div>",
"              </SheetContent>",
"            </Sheet>",
"          </div>",
"        </div>",
"      </div>",
"    </nav>",
"  );",
"}",
].join('\n');
fs.writeFileSync('src/components/Navbar.tsx', content);
console.log('Navbar written');
