import i18n from 'i18next';
  import { initReactI18next } from 'react-i18next';
  import LanguageDetector from 'i18next-browser-languagedetector';
  import { extendedEn } from './i18n/extended-en';
  import { legalEn } from './i18n/legal-en';
  import { legalJa } from './i18n/legal-ja';
  import { legalKo } from './i18n/legal-ko';
  import { legalDe } from './i18n/legal-de';
  import { legalEs } from './i18n/legal-es';
  import { legalFr } from './i18n/legal-fr';
  import { legalZh } from './i18n/legal-zh';
  import { tokushohoByLocale } from './i18n/tokushoho-locales';
  import { kyotoJaOverrides } from './i18n/kyoto-ja';

  function deepMerge<T extends Record<string, unknown>>(target: T, source: Record<string, unknown>): T {
    const out = { ...target } as Record<string, unknown>;
    for (const key of Object.keys(source)) {
      const sv = source[key];
      const tv = out[key];
      if (sv && typeof sv === 'object' && !Array.isArray(sv)) {
        out[key] = deepMerge((tv as Record<string, unknown>) ?? {}, sv as Record<string, unknown>);
      } else {
        out[key] = sv;
      }
    }
    return out as T;
  }

  const RTL_LANGUAGES = new Set(['ar', 'he']);

  function setDocumentDirection(lng: string) {
    const base = lng.split('-')[0];
    const dir = RTL_LANGUAGES.has(base) ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lng;
  }

  const resources: Record<string, { translation: Record<string, any> }> = {
    en: { translation: {
      nav: { home:'Home', brand:'Ramen Anime', shop:'Shop', prints3d:'3D Prints', cards:'Trading Cards', contact:'Contact', social:'Social Forum', login:'Join / Login', terms:'Terms', friends:'Friends', profile:'Profile', marketplace:'Marketplace', myProfile:'My Profile', admin:'Admin Dashboard', logout:'Logout', menu:'Menu', language:'Language', donate:'Donate' },
      hero: { title:'ラーメンアニメ', subtitle:'Your one-stop shop for custom 3D printed anime goods and trading cards. Handcrafted with passion. Shipped with care.', shopNow:'Shop Now', joinCommunity:'Join Community' },
      home: { badge:'Community Marketplace + Auctions', browseMarketplace:'Browse Marketplace', startSelling:'Start Selling', authenticityVerified:'Authenticity Verified', liveAuctionsBadge:'Live Auctions', globalShipping:'Global Shipping', categories:{ tradingCards:'Trading Cards', prints3d:'3D Prints', figures:'Figures', apparel:'Apparel', accessories:'Accessories', auctions:'Auctions' }, liveAuctions:{ title:'Live Auctions', subtitle:'Bid on rare anime collectibles in real time', viewAll:'View All', auction:'Auction', bids:'{{count}} bids', seller:'Seller', ended:'Ended', timeLeftDays:'{{days}}d {{hours}}h left', timeLeftHours:'{{hours}}h {{minutes}}m left', empty:'No active auctions. Be the first to list one!', startAuction:'Start an Auction' }, trending:{ title:'Trending Now', subtitle:'Most popular items this week', explore:'Explore', current:'Current: {{price}}' }, newArrivals:{ title:'New Arrivals', subtitle:'Fresh listings from the community', seeAll:'See All' }, whySell:{ title:'Why Sell Here?', subtitle:'Built for anime collectors, by anime collectors', features:{ auctions:{ title:'Live Auctions', desc:'Real-time bidding with anti-snipe protection.' }, authenticity:{ title:'Authenticity Scan', desc:'Listings scanned before going live.' }, ratings:{ title:'Seller Ratings', desc:'Build reputation with verified reviews.' }, offers:{ title:'Price Negotiation', desc:'Buyers can make offers on fixed-price items.' }, currency:{ title:'Multi-Currency', desc:'Live exchange rates from the ECB.' }, community:{ title:'Community', desc:'Forum, messaging, and Q&A on listings.' }, categories:{ title:'All Categories', desc:'Cards, 3D prints, figures, apparel, and more.' }, watchlist:{ title:'Watchlist', desc:'Track auctions and get outbid alerts.' } } }, stats:{ languages:'Languages', copyrightBot:'Copyright Bot' }, cta:{ title:'Start Selling Today', desc:'List your first item in under 2 minutes on Ramen Anime.', listItem:'List an Item', joinCommunity:'Join Community' } },
      features: { prints:'Custom 3D Prints', printsDesc:'Made to order anime-themed prints with premium PLA and resin', cards:'Trading Cards', cardsDesc:'Pokemon, One Piece, Naruto, Dragon Ball, Yu-Gi-Oh & more', shipping:'Fast Shipping', shippingDesc:'Quick dispatch on all orders with tracking', verified:'Ramen Anime Verified', verifiedDesc:'Trusted seller with 100+ positive reviews' },
      products: { title:'Our Products', subtitle:'Shop Collection', viewAll:'View All Products', orderNow:'Order Now', viewListing:'View on Ramen Anime' },
      about: { title:'About Us', subtitle:'Passion for Anime & Gaming', desc:'Ramen Anime is an online shop run by a fellow anime fan and gamer. We create custom 3D printed anime merchandise and sell curated trading card collections. Every product is made and shipped with care.', customers:'Happy Customers', designs:'3D Print Designs', cardsListed:'Cards Listed' },
      contact: { title:'Contact Us', subtitle:'Get In Touch', desc:'Questions about an order? Custom 3D print request? Want to know what trading cards we have in stock? Reach out anytime.', email:'Email', responseTime:'Response Time', shippingFrom:'Shipping', sendMessage:'Send Message', name:'Name', subject:'Subject', message:'Message' },
      footer: { shop:'Shop', community:'Community', getInTouch:'Get in Touch', rights:'All rights reserved.' },
      ageGate: { title:'Age Verification Required', subtitle:'You must be 18 or older to enter this site', desc:'This website contains content related to collectible trading cards and anime merchandise. By entering, you confirm you are of legal age in your jurisdiction.', confirm:'I am 18 or older', exit:'Leave Site', readTerms:'Read Terms of Service', readPrivacy:'Read Privacy Policy', notice:'By clicking "I am 18 or older", you agree to our Terms of Service and Privacy Policy.' },
      marketplace: { title:'User Marketplace', subtitle:'Buy & Sell Anime Goods', sellItem:'Sell an Item', buyNow:'Buy Now', condition:'Condition', price:'Price', seller:'Seller', contactSeller:'Contact Seller', new:'New', used:'Used', likeNew:'Like New' },
      forum: { title:'Social Forum', subtitle:'Connect with fellow anime fans', newPost:'New Post', search:'Search posts...', category:'Category', noPosts:'No posts yet', beFirst:'Be the first to start a conversation!', comments:'Comments', likes:'Likes', views:'Views', addComment:'Add a Comment', postComment:'Post Comment', sort_latest:'Latest', sort_popular:'Popular', sort_pinned:'Pinned', load_more:'Load More', start_discussion:'Start a Discussion', post_title:'Post Title', post_content:"What's on your mind?", posting:'Posting...', create_post:'Create Post', recent_activity:'Recent Activity', top_contributors:'Top Contributors', cat_general:'General Discussion', cat_general_desc:'Chat about anything anime and manga related', cat_anime:'Anime & Manga', cat_anime_desc:'Discussions about specific series, episodes, and chapters', cat_gaming:'Gaming', cat_gaming_desc:'Anime games, gacha, and gaming culture', cat_trading:'Trading Cards', cat_trading_desc:'Pokemon, One Piece, Yu-Gi-Oh, and more TCG talk', cat_3dprints:'3D Prints & Merch', cat_3dprints_desc:'Show off your prints, discuss techniques, share shops', cat_offtopic:'Off Topic', cat_offtopic_desc:'Non-anime discussions, life, and random chat' },
      profile: { aboutMe:'About Me', interests:'Interests', profileSong:'Profile Song', favAnime:'Favorite Anime', favGames:'Favorite Games', editProfile:'Edit Profile', addFriend:'Add Friend', friends:'Friends', mood:'Mood', location:'Location', website:'Website', welcome:'Welcome! Set up your profile', createProfile:'Create your profile to share with the Ramen Anime community.', notFound:'Profile not found', noProfile:"This user hasn\'t set up their profile yet.", setupBtn:'Set Up Profile', editBtn:'Edit Profile', saveBtn:'Save Profile', saving:'Saving...', saveSuccess:'Profile saved!', saveFailed:'Save failed: {{message}}', friendRequestSent:'Friend request sent!', createTitle:'Create Your Profile', editTitle:'Edit Your Profile', noBio:'No bio yet.', noInterests:'No interests listed yet.', noFavorites:'No favorites yet.', forumPostsPlaceholder:'Forum posts will appear here.', listen:'Listen', displayName:'Display Name', headline:'Headline', bio:'About Me', recentPosts:'Recent Forum Posts', viewForum:'View Forum', message:'Message', tabEarnings:'Earnings', connectStripe:'Connect Stripe to receive payouts', connectStripeBtn:'Connect Stripe', mySales:'My sales', myPurchases:'My purchases', noSales:'No sales yet', noPurchases:'No purchases yet', orderNumber:'Order' },
      terms: { title:'Terms of Service', acceptRequired:'Terms of Service Required', acceptDesc:'Before you can access the ラーメンアニメ Social Forum, you must read and accept our Terms of Service.', acceptBtn:'I Accept the Terms of Service', readFull:'Read Full Terms', acceptIntro:'By clicking Accept, you agree to:', ruleAge:'Be at least 13 years of age (18 without parental consent)', ruleContent:'Not post hateful, threatening, or explicit content', ruleHarassment:'Not harass or abuse other community members', ruleSpam:'Not use the service for spam or unsolicited advertising', ruleIP:'Respect intellectual property rights', ruleLaw:'Comply with all applicable laws in your jurisdiction', acceptPrivacy:'You also acknowledge our Privacy Policy and Terms of Service. These terms only need to be accepted once per account.', privacyLink:'Privacy Policy', termsLink:'Terms of Service', saving:'Saving...', acceptFailed:'Failed to accept terms: {{message}}' },
      common: { accessDenied:'Access denied', accessDeniedAdmin:'This area is restricted to administrators only.' },
      login: { backToHome:'Back to Home', welcomeBack:'Welcome Back', joinTitle:'Join ラーメンアニメ', signInDesc:'Sign in to access your profile, forum, and marketplace.', joinDesc:'Create an account to connect with fellow anime fans.', username:'Username', usernamePlaceholder:'your_username', usernameHint:'3-30 characters. Letters, numbers, and underscores only.', email:'Email', emailHint:'required for account recovery', password:'Password', passwordPlaceholder:'Enter password', passwordHint:'Minimum 8 characters with uppercase, lowercase, number, and special character.', showPassword:'Show password', hidePassword:'Hide password', forgotPassword:'Forgot password?', signIn:'Sign In', createAccount:'Create Account', signingIn:'Signing in...', creating:'Creating account...', newHere:'New here?', alreadyMember:'Already a member?', readTerms:'Read Terms of Service', agreeNotice:'By creating an account or signing in, you agree to our Terms of Service. You must be 18+ to access the social forum and marketplace.', loginFailed:'Login failed', registerFailed:'Registration failed', welcomeToast:'Welcome back!', registerToast:'Account created! Welcome to ラーメンアニメ.', invalidPassword:'Password does not meet all requirements.', captchaRequired:'Please complete the CAPTCHA verification.', sessionFailed:'Sign-in succeeded but the session could not be saved. Try again or use a private window without strict cookie blocking.', req1:'At least 8 characters', req2:'One uppercase letter', req3:'One lowercase letter', req4:'One number', req5:'One special character (!@#$% etc.)' },
      forgotPassword: { title:'Reset Password', desc:'Enter your email and we will send you a reset link.', send:'Send Reset Link', sending:'Sending...', sent:'Check your email', sentDesc:'If an account exists with that email, we have sent a password reset link.', backToLogin:'Back to Login', emailPlaceholder:'you@example.com', requestFailed:'Request failed', emailLabel:'Email Address' },
      resetPassword: { title:'Set New Password', desc:'Enter your new password below.', newPassword:'New Password', confirmPassword:'Confirm Password', resetBtn:'Reset Password', resetting:'Resetting...', passwordsMatch:'Passwords do not match.', invalidPassword:'Password does not meet all requirements.', backToLogin:'Back to Login', success:'Password updated', successDesc:'You can now sign in with your new password.', resetFailed:'Reset failed', requestNew:'Request New Link' },
      admin: { title:'Admin Dashboard', subtitle:'Manage your Ramen Anime community', accessDenied:'Access denied. Admin only.', overview:'Overview', users:'Users', forum:'Forum', posts:'Posts', listings:'Listings', marketplaceTab:'Marketplace', donations:'Donations', totalUsers:'Total Users', totalPosts:'Total Posts', activeListings:'Active Listings', totalDonations:'Completed Donations', noUsers:'No users found', noPosts:'No posts found', noListings:'No listings found', noDonations:'No completed donations yet', role:'Role', joined:'Joined', actions:'Actions', makeAdmin:'Make Admin', revokeAdmin:'Revoke Admin', delete:'Delete', deletePost:'Delete Post', deleteConfirm:'Are you sure?', approve:'Approve', reject:'Reject', comments:'Comments', admins:'Admins', banned:'Banned', tosAccepted:'TOS Accepted', totalVisits:'Total Visits', orders:'Orders', paidOrders:'Paid Orders', gmv:'GMV (paid)', platformFees:'Platform fees', donationRevenue:'Donation revenue', usersCount:'Users ({{count}})', forumPostsCount:'Forum Posts ({{count}})', listingsCount:'Listings ({{count}})', donationsCount:'Completed donations ({{count}})', username:'Username', status:'Status', view:'View', active:'Active', anonymous:'Anonymous', amount:'Amount', donor:'Donor', postDeleted:'Post deleted', listingUpdated:'Listing updated', roleUpdated:'Role updated', userBanned:'User banned', userUnbanned:'User unbanned', deleteConfirmShort:'Delete?', byAuthor:'by {{name}} | {{likes}} likes', bySeller:'by {{seller}} | {{price}}', unknown:'Unknown', analyticsLink:'Analytics', swarmLink:'Swarm', siteDoctorLink:'Site Doctor', copyrightQueue:'Copyright review queue', sellerLabel:'Seller', paymentMethod:'Method' },
      legal: { termsTitle:'Terms of Service', privacyTitle:'Privacy Policy', lastUpdated:'Last Updated: {{date}}', applicableLaw:'Applicable Law: {{law}}', yourRegion:'Your Region: {{region}}', backHome:'Back to Home', defaults: { globalPrivacyLaw:'Global Best Practices', globalTermsLaw:'Global Standards', globalRegion:'Global', internationalPrivacyStandards:'international privacy standards', verifiableParentalConsent:'verifiable parental consent', appropriateSafeguards:'appropriate safeguards', limited:'Limited', yesWithLaw:'Yes - {{law}}', cookieConsentRequired:'Under {{law}}, we require your consent before placing non-essential cookies. You can manage preferences through our cookie consent banner.', cookieConsentBrowser:'You can manage cookie preferences through your browser settings.' } },
      sellerStripe: { connectedTitle:'Stripe connected', incompleteTitle:'Stripe setup incomplete', connectedDesc:'Your seller payout account is linked to Ramen Anime.', incompleteDesc:'Connect again to accept card payments.', createListing:'Create a listing', backMarketplace:'Back to marketplace', readyToast:'Payment account is ready.', progressToast:'Stripe setup in progress.' },
      donations: { title:'Support ラーメンアニメ', subtitle:'Keep the community growing', desc:'Your support helps keep the servers running, the store stocked, and new features coming. Every contribution is deeply appreciated.', payWithPayPal:'Donate with PayPal', sendViaRevolut:'Send via Revolut', copyLink:'Copy Revolut Link', copied:'Copied!', recentDonors:'Recent Supporters', anonymous:'Anonymous', thankYou:'Thank you for your support!', goal:'Goal', raised:'Raised', totalDonations:'Total Raised', donorCount:'Supporters', noDonations:'Be the first to support us!', loadingPayPal:'Loading PayPal...', paypalTitle:'PayPal', revolutTitle:'Revolut', paypalDesc:'Donate securely using your card or PayPal balance.', revolutDesc:'Send via Revolut, then confirm below so we can update our records.', amountUsd:'Amount (USD)', openRevolut:'Open Revolut', confirmRevolut:'I sent this amount via Revolut', revolutRecorded:'Thank you! Your Revolut donation was recorded.', paypalRecorded:'Thank you! Your PayPal donation was recorded.', recordFailed:'Could not record donation. Please contact support.', revolutAmountRequired:'Enter the amount you sent via Revolut.', raisedSummary:'${{amount}} raised by {{count}} supporters', donorName:'Display name (optional)', donorNamePlaceholder:'How we should thank you', message:'Message (optional)', messagePlaceholder:'A short note with your gift', disclaimer:'All donations are voluntary and non-refundable. Ramen Anime is not a registered non-profit.' },
      listing: { back:'Back', buy_now:'Buy Now', place_bid:'Place Bid', current_bid:'Current Bid', time_left:'Time Left', instant_buy:'Buy Now', condition:'Condition', seller:'Seller', shipping:'Shipping', shippingEstimate:'Shipping estimate', shippingPaidBy:'Paid by {{payer}}', ask_question:'Ask a Question', add_watchlist:'Add to Watchlist', share:'Share', bid_history:'Bid History', recent_bids:'Recent Bids', make_offer:'Make Offer', verified_seller:'Verified Seller', authenticityDeclared:'Seller declared item authentic', description:'Description', similar_items:'Similar Items', auction_ended:'Auction Ended', quantity:'Quantity', your_bid:'Your Bid', min_bid:'Minimum Bid', checkout:'Checkout', no_bids:'No bids yet. Be the first!', auction:'Auction', fixed:'Fixed Price', loading:'Loading listing...', not_found:'Listing not found', ends_in:'Ends in', buy_price:'Buy Price', bid_now:'Bid Now', contacting:'Contacting...', contact_seller:'Contact Seller', watchlisted:'Watchlisted', watch:'Watch', unwatch:'Unwatch', paymentSuccess:'Payment successful', sellerNotReadyBuy:'Seller cannot accept payments yet', sellerNotReady:'Seller has not finished payment setup', redirecting:'Redirecting to checkout...', payWithCard:'Pay with card', paymentRequired:'Payment required', orderLabel:'Order {{number}}', platformFee:'Platform fee (5%)', sellerReceives:'Seller receives', total:'Total', confirming:'Confirming...', markPaidDev:'I have paid (dev only)', liveUpdates:'Live updates', autoBid:'Auto-bid', autoBidMaxPlaceholder:'Max auto-bid (USD)', autoBidSet:'Auto-bid active', paymentDeadline:'Pay within 48 hours' },
      messages: { title:'Messages', login_required:'Login Required', login_to_view:'Please log in to view your messages', no_messages:'No messages yet', type_message:'Type a message...', send:'Send', conversation:'Conversation', new_message:'New Message', coming_soon:'Full messaging coming soon. Use the Contact Seller button on listings to reach sellers directly.' },
      orders: { title:'Orders', my_purchases:'My Purchases', my_sales:'My Sales', no_purchases:'No purchases yet', no_sales:'No sales yet', order_number:'Order #', status:'Status', total:'Total', items:'Items', track:'Track Order', view_details:'View Details', pending:'Pending', paid:'Paid', shipped:'Shipped', delivered:'Delivered', cancelled:'Cancelled', refunded:'Refunded', placed_on:'Placed on', buyer:'Buyer', seller:'Seller', loading:'Loading orders...', login_required:'Please log in to view your orders' },
      createListing: { title:'Create Listing', subtitle:'List your anime goods for sale', item_title:'Item Title', item_title_ph:'e.g. Naruto Shippuden Figure - Sage Mode', description:'Description', description_ph:'Describe your item in detail - condition, authenticity, included accessories...', price:'Price (USD)', condition:'Condition', category:'Category', images:'Photos', listing_type:'Listing Type', auction:'Auction', fixed_price:'Fixed Price', duration:'Duration', duration_7:'7 days', duration_14:'14 days', duration_30:'30 days', submit:'List Item', creating:'Creating...', success:'Listing created!', error:'Failed to create listing', add_images:'Add Photos', max_images:'Max 10 photos', ai_suggest:'AI Suggest', ai_analyzing:'Analyzing...', preview:'Preview', new:'New', like_new:'Like New', used:'Used', cat_figures:'Anime Figures', cat_manga:'Manga / Books', cat_art:'Art / Cels', cat_collectibles:'Collectibles', cat_gaming:'Gaming', cat_cards:'Trading Cards', cat_apparel:'Apparel', cat_accessories:'Accessories', cat_3d:'Custom 3D Prints', cat_other:'Other', login_required:'Please log in to create a listing', min_images:'Add at least one photo', min_price:'Price must be at least $0.01', title_required:'Title is required' },
      friends: { title:'Friends', my_friends:'My Friends', pending_requests:'Pending Requests', no_friends:'No friends yet', no_requests:'No pending requests', accept:'Accept', decline:'Decline', remove:'Remove', message:'Message', friend_since:'Friends since', mutual:'mutual friends', online:'Online', offline:'Offline', loading:'Loading...', view_profile:'View Profile', request_sent:'Request Sent', add_friend:'Add Friend', remove_friend:'Remove Friend', confirm_remove:'Remove this friend?' },
      orderDetail: { back:'Back to Orders', order_summary:'Order Summary', order_status:'Order Status', pending:'Pending Payment', payment_received:'Payment Received', shipped:'Shipped', delivered:'Delivered', cancelled:'Cancelled', items_ordered:'Items Ordered', seller_info:'Seller', buyer_info:'Buyer', shipping_address:'Shipping Address', payment_method:'Payment', contact_seller:'Contact Seller', contact_buyer:'Contact Buyer', open_dispute:'Open Dispute', submit_review:'Leave Review', track_package:'Track Package', total:'Total', subtotal:'Subtotal', shipping_cost:'Shipping', loading:'Loading order...', not_found:'Order not found', mark_shipped:'Mark as Shipped', confirm_delivery:'Confirm Delivery', order_number:'Order', placed:'Placed', quantity:'Qty' },
      geoBlock: { title:'Service Not Available', subtitle:'This service is not available in your region.', detected:'Detected:', retry:'Retry Detection', select_country:'Select Country Manually', not_available:'We are not yet available in your region. We currently serve select countries in Asia, North America, and the EU.', checking:'Checking your location...', available_in:'Available countries' },
    }},

    ja: { translation: {
      nav: { home:'ホーム', brand:'Ramen Anime', shop:'ショップ', prints3d:'3Dプリント', cards:'トレカ', contact:'お問い合わせ', social:'掲示板', login:'ログイン', terms:'規約', friends:'友達', profile:'プロフィール', marketplace:'マーケット', myProfile:'マイプロフィール', admin:'管理ダッシュボード', logout:'ログアウト', menu:'メニュー', language:'言語', donate:'寄付' },
      hero: { title:'ラーメンアニメ', subtitle:'カスタム3Dプリントのアニメグッズとトレーディングカードの専門店。情熱を込めて作り、丁寧に発送します。', shopNow:'今すぐ購入', joinCommunity:'コミュニティに参加' },
      features: { prints:'カスタム3Dプリント', printsDesc:'高品質PLAとレジンで作るアニメテーマのプリント', cards:'トレーディングカード', cardsDesc:'ポケモン、ワンピース、ナルト、ドラゴンボール、遊戯王など', shipping:'速達配送', shippingDesc:'すべての注文を追跡付きで迅速発送', verified:'the marketplace認証', verifiedDesc:'100件以上の好評価を持つ信頼できる出品者' },
      products: { title:'商品一覧', subtitle:'ショップコレクション', viewAll:'すべての商品を見る', orderNow:'注文する', viewListing:'マーケットで見る' },
      about: { title:'私たちについて', subtitle:'アニメとゲームへの情熱', desc:'ラーメンアニメは、アニメファン兼ゲーマーが運営するオンラインゲームショップです。', customers:'お客様', designs:'3Dプリントデザイン', cardsListed:'出品カード数' },
      contact: { title:'お問い合わせ', subtitle:'連絡先', desc:'注文の質問やカスタム依頼はいつでもどうぞ。', email:'メール', responseTime:'返信時間', shippingFrom:'発送元', sendMessage:'送信', name:'お名前', subject:'件名', message:'メッセージ' },
      footer: { shop:'ショップ', community:'コミュニティ', getInTouch:'お問い合わせ', rights:'All rights reserved.' },
      ageGate: { title:'年齢確認が必要です', subtitle:'18歳以上であることを確認してください', desc:'このサイトはトレーディングカードとアニメグッズに関するコンテンツを含みます。', confirm:'18歳以上です', exit:'サイトを離れる', readTerms:'利用規約を読む', readPrivacy:'プライバシーポリシーを読む', notice:'クリックすることで利用規約とプライバシーポリシーに同意します。' },
      marketplace: { title:'ユーザーマーケット', subtitle:'アニメグッズの売買', sellItem:'出品する', condition:'状態', price:'価格', seller:'出品者', contactSeller:'出品者に連絡', new:'新品', used:'中古', likeNew:'ほぼ新品' },
      forum: { title:'掲示板', subtitle:'仲間のアニメファンとつながる', newPost:'新規投稿', search:'投稿を検索...', category:'カテゴリ', noPosts:'まだ投稿がありません', beFirst:'最初の投稿者になりましょう！', comments:'コメント', likes:'いいね', views:'閲覧数', addComment:'コメントを追加', postComment:'コメントを投稿', sort_latest:'最新', sort_popular:'人気', sort_pinned:'固定', load_more:'もっと見る', start_discussion:'ディスカッションを始める', post_title:'タイトル', post_content:'何を話したいですか？', posting:'投稿中...', create_post:'投稿する', recent_activity:'最近のアクティビティ', top_contributors:'トップ貢献者', cat_general:'一般', cat_general_desc:'アニメや漫画についてなんでも話そう', cat_anime:'アニメ・漫画', cat_anime_desc:'特定のシリーズやエピソードの話', cat_gaming:'ゲーム', cat_gaming_desc:'アニメゲームやガチャ、ゲーム文化', cat_trading:'トレーディングカード', cat_trading_desc:'ポケモン、ワンピース、遊戯王など', cat_3dprints:'3Dプリント・グッズ', cat_3dprints_desc:'プリントを披露し、技術を議論する', cat_offtopic:'雑談', cat_offtopic_desc:'アニメ以外の話題や日常' },
      profile: { aboutMe:'自己紹介', interests:'興味', profileSong:'プロフィール曲', favAnime:'好きなアニメ', favGames:'好きなゲーム', editProfile:'プロフィール編集', addFriend:'友達追加', friends:'友達', mood:'気分', location:'場所', website:'ウェブサイト', welcome:'ようこそ！プロフィールを設定してください', createProfile:'MySpaceスタイルのプロフィールを作成しましょう。', notFound:'プロフィールが見つかりません', noProfile:'このユーザーはまだプロフィールを設定していません。', setupBtn:'プロフィール設定', editBtn:'プロフィール編集', saveBtn:'保存', saving:'保存中...', displayName:'表示名', headline:'ヘッドライン', bio:'自己紹介', recentPosts:'最近の投稿', viewForum:'掲示板を見る' },
      terms: { title:'利用規約', acceptRequired:'利用規約の同意が必要です', acceptDesc:'ラーメンアニメの掲示板にアクセスする前に、利用規約をお読みください。', acceptBtn:'規約に同意します', readFull:'規約全文を読む' },
      login: { backToHome:'ホームに戻る', welcomeBack:'おかえりなさい', joinTitle:'ラーメンアニメに参加', signInDesc:'プロフィール、掲示板、マーケットにアクセス。', joinDesc:'アニメファンと繋がるアカウントを作成。', username:'ユーザー名', usernameHint:'3〜30文字。英数字とアンダースコア。', email:'メール', emailHint:'アカウント復旧に必要', password:'パスワード', passwordHint:'大文字・小文字・数字・特殊文字含む8文字以上。', showPassword:'表示', hidePassword:'隠す', forgotPassword:'パスワードを忘れた？', signIn:'サインイン', createAccount:'アカウント作成', signingIn:'サインイン中...', creating:'作成中...', newHere:'初めてですか？', alreadyMember:'すでに会員ですか？', readTerms:'利用規約を読む', agreeNotice:'登録・ログインで利用規約に同意します。', loginFailed:'ログイン失敗', registerFailed:'登録失敗', welcomeToast:'おかえりなさい！', registerToast:'アカウントが作成されました！', invalidPassword:'パスワードが要件を満たしていません。', req1:'8文字以上', req2:'大文字を含む', req3:'小文字を含む', req4:'数字を含む', req5:'特殊文字を含む' },
      forgotPassword: { title:'パスワードリセット', desc:'メールアドレスを入力してください。', send:'リセットリンクを送る', sending:'送信中...', sent:'メールを確認してください', sentDesc:'アカウントが存在する場合、リセットリンクを送信しました。', backToLogin:'ログインに戻る', emailPlaceholder:'your@email.com', requestFailed:'リクエスト失敗', emailLabel:'メールアドレス' },
      resetPassword: { title:'新しいパスワードを設定', desc:'新しいパスワードを入力してください。', newPassword:'新しいパスワード', confirmPassword:'パスワードの確認', resetBtn:'パスワードをリセット', resetting:'リセット中...', passwordsMatch:'パスワードが一致しません。', invalidPassword:'パスワードが要件を満たしていません。', backToLogin:'ログインに戻る', success:'パスワードが更新されました', successDesc:'新しいパスワードでサインインできます。', resetFailed:'リセット失敗', requestNew:'新しいリンクをリクエスト' },
      admin: { title:'管理ダッシュボード', overview:'概要', users:'ユーザー', posts:'投稿', listings:'出品', donations:'寄付', totalUsers:'総ユーザー数', totalPosts:'総投稿数', activeListings:'有効な出品', totalDonations:'総寄付額', noUsers:'ユーザーなし', noPosts:'投稿なし', noListings:'出品なし', noDonations:'まだ寄付はありません', role:'役割', joined:'参加日', actions:'操作', makeAdmin:'管理者にする', revokeAdmin:'管理者を解除', delete:'削除', deletePost:'投稿を削除', deleteConfirm:'よろしいですか？', approve:'承認', reject:'拒否' },
      donations: { title:'ラーメンアニメをサポート', subtitle:'コミュニティを支えよう', desc:'サポートがサーバー維持、在庫補充、新機能開発に役立ちます。', payWithPayPal:'PayPalで寄付', sendViaRevolut:'Revolutで送る', copyLink:'Revolutリンクをコピー', copied:'コピーしました！', recentDonors:'最近の支援者', anonymous:'匿名', thankYou:'ご支援ありがとうございます！', goal:'目標', raised:'達成', totalDonations:'合計寄付額', donorCount:'支援者数', noDonations:'最初の支援者になりましょう！' },
      listing: { back:'戻る', buy_now:'今すぐ購入', place_bid:'入札する', current_bid:'現在の入札額', time_left:'残り時間', instant_buy:'即決購入', condition:'状態', seller:'出品者', shipping:'配送', ask_question:'質問する', add_watchlist:'ウォッチリストに追加', share:'シェア', bid_history:'入札履歴', recent_bids:'最近の入札', make_offer:'オファーする', verified_seller:'認証済み出品者', description:'説明', similar_items:'類似商品', auction_ended:'オークション終了', quantity:'数量', your_bid:'あなたの入札額', min_bid:'最低入札額', checkout:'購入手続き', no_bids:'まだ入札なし。最初の入札者になろう！', auction:'オークション', fixed:'固定価格', loading:'読み込み中...', not_found:'商品が見つかりません', ends_in:'終了まで', buy_price:'購入価格', bid_now:'入札する', contacting:'連絡中...', contact_seller:'出品者に連絡', watchlisted:'ウォッチ済み', watch:'ウォッチ', unwatch:'ウォッチ解除' },
      messages: { title:'メッセージ', login_required:'ログインが必要', login_to_view:'メッセージを見るにはログインしてください', no_messages:'メッセージなし', type_message:'メッセージを入力...', send:'送信', conversation:'会話', new_message:'新しいメッセージ', coming_soon:'完全なメッセージ機能は近日公開。出品ページの「出品者に連絡」ボタンをご利用ください。' },
      orders: { title:'注文', my_purchases:'購入履歴', my_sales:'販売履歴', no_purchases:'購入履歴なし', no_sales:'販売履歴なし', order_number:'注文番号', status:'ステータス', total:'合計', items:'商品', track:'追跡', view_details:'詳細を見る', pending:'保留中', paid:'支払済', shipped:'発送済', delivered:'配達済', cancelled:'キャンセル', refunded:'返金済', placed_on:'注文日', buyer:'購入者', seller:'出品者', loading:'読み込み中...', login_required:'注文を見るにはログインしてください' },
      createListing: { title:'出品する', subtitle:'アニメグッズを出品しよう', item_title:'タイトル', item_title_ph:'例：ナルト疾風伝 仙人モードフィギュア', description:'説明', description_ph:'商品の状態、真正性、付属品などを詳しく説明...', price:'価格（USD）', condition:'状態', category:'カテゴリ', images:'写真', listing_type:'出品タイプ', auction:'オークション', fixed_price:'固定価格', duration:'期間', duration_7:'7日間', duration_14:'14日間', duration_30:'30日間', submit:'出品する', creating:'出品中...', success:'出品完了！', error:'出品に失敗しました', add_images:'写真を追加', max_images:'最大10枚', ai_suggest:'AI提案', ai_analyzing:'分析中...', preview:'プレビュー', new:'新品', like_new:'ほぼ新品', used:'中古', cat_figures:'アニメフィギュア', cat_manga:'漫画・本', cat_art:'アート・セル', cat_collectibles:'コレクタブル', cat_gaming:'ゲーム', cat_cards:'トレーディングカード', cat_apparel:'アパレル', cat_accessories:'アクセサリー', cat_3d:'カスタム3Dプリント', cat_other:'その他', login_required:'出品するにはログインしてください', min_images:'写真を少なくとも1枚追加してください', min_price:'価格は$0.01以上必要です', title_required:'タイトルは必須です' },
      friends: { title:'友達', my_friends:'マイフレンド', pending_requests:'保留中のリクエスト', no_friends:'友達がまだいません', no_requests:'保留中のリクエストなし', accept:'承認', decline:'拒否', remove:'削除', message:'メッセージ', friend_since:'友達になった日', mutual:'共通の友達', online:'オンライン', offline:'オフライン', loading:'読み込み中...', view_profile:'プロフィールを見る', request_sent:'リクエスト送信済み', add_friend:'友達追加', remove_friend:'友達を削除', confirm_remove:'友達を削除しますか？' },
      orderDetail: { back:'注文に戻る', order_summary:'注文概要', order_status:'注文状況', pending:'支払い待ち', payment_received:'支払い確認', shipped:'発送済', delivered:'配達済', cancelled:'キャンセル', items_ordered:'注文商品', seller_info:'出品者', buyer_info:'購入者', shipping_address:'配送先', payment_method:'支払い方法', contact_seller:'出品者に連絡', contact_buyer:'購入者に連絡', open_dispute:'異議を申し立てる', submit_review:'レビューを投稿', track_package:'荷物を追跡', total:'合計', subtotal:'小計', shipping_cost:'送料', loading:'読み込み中...', not_found:'注文が見つかりません', mark_shipped:'発送済みにする', confirm_delivery:'受け取り確認', order_number:'注文', placed:'注文日', quantity:'数量' },
      geoBlock: { title:'サービス利用不可', subtitle:'このサービスはお住まいの地域では利用できません。', detected:'検出された地域：', retry:'再検出', select_country:'国を手動で選択', not_available:'お住まいの地域ではまだサービスを提供していません。', checking:'位置情報を確認中...', available_in:'利用可能な国' },
    }},

    ko: { translation: {
      nav: { home:'홈', brand:'Ramen Anime', shop:'쇼핑', prints3d:'3D 프린트', cards:'트레이딩 카드', contact:'문의', social:'소셜 포럼', login:'가입/로그인', terms:'약관', friends:'친구', profile:'프로필', marketplace:'마켓플레이스', myProfile:'내 프로필', admin:'관리자 대시보드', logout:'로그아웃', menu:'메뉴', language:'언어', donate:'후원' },
      hero: { title:'ラーメンアニメ', subtitle:'커스텀 3D 프린트 애니메이션 굿즈와 트레이딩 카드 전문점. 열정으로 만들고, 정성껏 배송합니다.', shopNow:'지금 쇼핑하기', joinCommunity:'커뮤니티 참여' },
      features: { prints:'커스텀 3D 프린트', printsDesc:'프리미엄 PLA와 레진으로 제작한 주문형 애니메이션 프린트', cards:'트레이딩 카드', cardsDesc:'포켓몬, 원피스, 나루토, 드래곤볼, 유희왕 등', shipping:'빠른 배송', shippingDesc:'추적 서비스와 함께 신속한 발송', verified:'인증된 판매자', verifiedDesc:'100개 이상의 긍정적 리뷰를 가진 신뢰할 수 있는 판매자' },
      products: { title:'상품 목록', subtitle:'쇼핑 컬렉션', viewAll:'모든 상품 보기', orderNow:'주문하기', viewListing:'마켓에서 보기' },
      about: { title:'회사 소개', subtitle:'애니메이션 & 게임에 대한 열정', desc:'ラーメンアニメ는 애니메이션 팬이 운영하는 온라인 쇼핑몰입니다.', customers:'행복한 고객', designs:'3D 프린트 디자인', cardsListed:'등록된 카드 수' },
      contact: { title:'문의하기', subtitle:'연락처', desc:'주문 관련 질문이나 커스텀 의뢰가 있으시면 언제든지 연락주세요.', email:'이메일', responseTime:'응답 시간', shippingFrom:'배송 출발지', sendMessage:'메시지 보내기', name:'이름', subject:'제목', message:'내용' },
      footer: { shop:'쇼핑', community:'커뮤니티', getInTouch:'연락하기', rights:'모든 권리 보유.' },
      ageGate: { title:'연령 확인 필요', subtitle:'이 사이트에 접속하려면 18세 이상이어야 합니다', desc:'이 웹사이트는 수집 가능한 트레이딩 카드 및 애니메이션 관련 상품을 포함합니다.', confirm:'18세 이상입니다', exit:'사이트 떠나기', readTerms:'이용약관 읽기', readPrivacy:'개인정보처리방침 읽기', notice:'클릭함으로써 이용약관과 개인정보처리방침에 동의합니다.' },
      marketplace: { title:'유저 마켓플레이스', subtitle:'애니메이션 굿즈 사고팔기', sellItem:'물건 팔기', condition:'상태', price:'가격', seller:'판매자', contactSeller:'판매자 연락', new:'새 제품', used:'중고', likeNew:'새것에 가까운' },
      forum: { title:'소셜 포럼', subtitle:'애니메이션 팬들과 소통하기', newPost:'새 게시글', search:'게시글 검색...', category:'카테고리', noPosts:'아직 게시글이 없습니다', beFirst:'첫 번째 대화를 시작해보세요!', comments:'댓글', likes:'좋아요', views:'조회수', addComment:'댓글 추가', postComment:'댓글 게시', sort_latest:'최신순', sort_popular:'인기순', sort_pinned:'고정', load_more:'더 보기', start_discussion:'대화 시작', post_title:'제목', post_content:'무슨 생각을 하고 있나요?', posting:'게시 중...', create_post:'게시하기', recent_activity:'최근 활동', top_contributors:'최고 기여자', cat_general:'일반 토론', cat_general_desc:'애니메이션과 만화에 관한 모든 것', cat_anime:'애니메이션 & 만화', cat_anime_desc:'특정 시리즈, 에피소드, 챕터 토론', cat_gaming:'게임', cat_gaming_desc:'애니메이션 게임, 가챠, 게임 문화', cat_trading:'트레이딩 카드', cat_trading_desc:'포켓몬, 원피스, 유희왕 등 TCG', cat_3dprints:'3D 프린트 & 굿즈', cat_3dprints_desc:'프린트 자랑, 기술 토론, 쇼핑 공유', cat_offtopic:'기타', cat_offtopic_desc:'애니메이션 이외의 주제, 일상' },
      profile: { aboutMe:'자기소개', interests:'관심사', profileSong:'프로필 노래', favAnime:'좋아하는 애니메이션', favGames:'좋아하는 게임', editProfile:'프로필 수정', addFriend:'친구 추가', friends:'친구', mood:'기분', location:'위치', website:'웹사이트', welcome:'환영합니다! 프로필을 설정하세요', createProfile:'커뮤니티와 공유할 프로필을 만드세요.', notFound:'프로필을 찾을 수 없습니다', noProfile:'이 사용자는 아직 프로필을 설정하지 않았습니다.', setupBtn:'프로필 설정', editBtn:'프로필 수정', saveBtn:'저장', saving:'저장 중...', displayName:'표시 이름', headline:'한마디', bio:'자기소개', recentPosts:'최근 게시글', viewForum:'포럼 보기' },
      terms: { title:'이용약관', acceptRequired:'이용약관 동의 필요', acceptDesc:'ラーメンアニメ 소셜 포럼에 접근하려면 이용약관을 읽고 동의하세요.', acceptBtn:'약관에 동의합니다', readFull:'전체 약관 읽기' },
      login: { backToHome:'홈으로', welcomeBack:'다시 오셨군요', joinTitle:'ラーメンアニメ 가입', signInDesc:'프로필, 포럼, 마켓에 접근하려면 로그인하세요.', joinDesc:'애니메이션 팬들과 연결하는 계정을 만드세요.', username:'사용자명', usernameHint:'3-30자. 영문, 숫자, 밑줄만 가능.', email:'이메일', emailHint:'계정 복구에 필요', password:'비밀번호', passwordHint:'대소문자, 숫자, 특수문자 포함 8자 이상.', showPassword:'비밀번호 보기', hidePassword:'비밀번호 숨기기', forgotPassword:'비밀번호 찾기?', signIn:'로그인', createAccount:'계정 만들기', signingIn:'로그인 중...', creating:'생성 중...', newHere:'처음이신가요?', alreadyMember:'이미 회원이신가요?', readTerms:'이용약관 읽기', agreeNotice:'가입 또는 로그인으로 이용약관에 동의합니다.', loginFailed:'로그인 실패', registerFailed:'가입 실패', welcomeToast:'다시 오셨군요!', registerToast:'계정이 생성되었습니다!', invalidPassword:'비밀번호가 요건을 충족하지 않습니다.', req1:'8자 이상', req2:'대문자 포함', req3:'소문자 포함', req4:'숫자 포함', req5:'특수문자 포함' },
      forgotPassword: { title:'비밀번호 재설정', desc:'이메일을 입력하면 재설정 링크를 보내드립니다.', send:'재설정 링크 보내기', sending:'전송 중...', sent:'이메일을 확인하세요', sentDesc:'계정이 존재하면 비밀번호 재설정 링크를 보냈습니다.', backToLogin:'로그인으로 돌아가기', emailPlaceholder:'your@email.com', requestFailed:'요청 실패', emailLabel:'이메일 주소' },
      resetPassword: { title:'새 비밀번호 설정', desc:'새 비밀번호를 입력하세요.', newPassword:'새 비밀번호', confirmPassword:'비밀번호 확인', resetBtn:'비밀번호 재설정', resetting:'재설정 중...', passwordsMatch:'비밀번호가 일치하지 않습니다.', invalidPassword:'비밀번호가 요건을 충족하지 않습니다.', backToLogin:'로그인으로 돌아가기', success:'비밀번호 업데이트됨', successDesc:'새 비밀번호로 로그인할 수 있습니다.', resetFailed:'재설정 실패', requestNew:'새 링크 요청' },
      admin: { title:'관리자 대시보드', overview:'개요', users:'사용자', posts:'게시글', listings:'상품', donations:'후원', totalUsers:'총 사용자', totalPosts:'총 게시글', activeListings:'활성 상품', totalDonations:'총 후원액', noUsers:'사용자 없음', noPosts:'게시글 없음', noListings:'상품 없음', noDonations:'아직 후원이 없습니다', role:'역할', joined:'가입일', actions:'작업', makeAdmin:'관리자로 만들기', revokeAdmin:'관리자 해제', delete:'삭제', deletePost:'게시글 삭제', deleteConfirm:'확실합니까?', approve:'승인', reject:'거부' },
      donations: { title:'ラーメンアニメ 후원하기', subtitle:'커뮤니티를 함께 키워가요', desc:'여러분의 후원이 서버 유지, 재고 확보, 새로운 기능 개발에 도움이 됩니다.', payWithPayPal:'PayPal로 후원', sendViaRevolut:'Revolut으로 보내기', copyLink:'Revolut 링크 복사', copied:'복사됨!', recentDonors:'최근 후원자', anonymous:'익명', thankYou:'후원해 주셔서 감사합니다!', goal:'목표', raised:'달성', totalDonations:'총 후원액', donorCount:'후원자 수', noDonations:'첫 번째 후원자가 되어보세요!' },
      listing: { back:'뒤로', buy_now:'바로 구매', place_bid:'입찰하기', current_bid:'현재 입찰가', time_left:'남은 시간', instant_buy:'즉시 구매', condition:'상태', seller:'판매자', shipping:'배송', ask_question:'질문하기', add_watchlist:'관심 목록에 추가', share:'공유', bid_history:'입찰 내역', recent_bids:'최근 입찰', make_offer:'오퍼하기', verified_seller:'인증된 판매자', description:'설명', similar_items:'유사 상품', auction_ended:'경매 종료', quantity:'수량', your_bid:'입찰가', min_bid:'최소 입찰가', checkout:'결제하기', no_bids:'아직 입찰이 없습니다. 첫 입찰자가 되세요!', auction:'경매', fixed:'고정 가격', loading:'로딩 중...', not_found:'상품을 찾을 수 없습니다', ends_in:'종료까지', buy_price:'구매가', bid_now:'지금 입찰', contacting:'연락 중...', contact_seller:'판매자 연락', watchlisted:'관심 등록됨', watch:'관심', unwatch:'관심 해제' },
      messages: { title:'메시지', login_required:'로그인 필요', login_to_view:'메시지를 보려면 로그인하세요', no_messages:'메시지가 없습니다', type_message:'메시지 입력...', send:'보내기', conversation:'대화', new_message:'새 메시지', coming_soon:'전체 메시지 기능은 곧 출시됩니다. 상품 페이지의 판매자 연락 버튼을 이용하세요.' },
      orders: { title:'주문', my_purchases:'구매 내역', my_sales:'판매 내역', no_purchases:'구매 내역 없음', no_sales:'판매 내역 없음', order_number:'주문 번호', status:'상태', total:'합계', items:'상품', track:'추적하기', view_details:'상세 보기', pending:'대기 중', paid:'결제됨', shipped:'발송됨', delivered:'배달됨', cancelled:'취소됨', refunded:'환불됨', placed_on:'주문일', buyer:'구매자', seller:'판매자', loading:'로딩 중...', login_required:'주문을 보려면 로그인하세요' },
      createListing: { title:'상품 등록', subtitle:'애니메이션 굿즈를 팔아보세요', item_title:'상품명', item_title_ph:'예: 나루토 질풍전 선인 모드 피규어', description:'설명', description_ph:'상품 상태, 진품 여부, 부속품 등을 자세히 설명하세요...', price:'가격 (USD)', condition:'상태', category:'카테고리', images:'사진', listing_type:'등록 유형', auction:'경매', fixed_price:'고정 가격', duration:'기간', duration_7:'7일', duration_14:'14일', duration_30:'30일', submit:'상품 등록', creating:'등록 중...', success:'등록 완료!', error:'등록 실패', add_images:'사진 추가', max_images:'최대 10장', ai_suggest:'AI 제안', ai_analyzing:'분석 중...', preview:'미리보기', new:'새 제품', like_new:'새것에 가까운', used:'중고', cat_figures:'애니메이션 피규어', cat_manga:'만화/책', cat_art:'아트/셀', cat_collectibles:'수집품', cat_gaming:'게임', cat_cards:'트레이딩 카드', cat_apparel:'의류', cat_accessories:'악세서리', cat_3d:'커스텀 3D 프린트', cat_other:'기타', login_required:'상품 등록하려면 로그인하세요', min_images:'사진을 하나 이상 추가하세요', min_price:'가격은 $0.01 이상이어야 합니다', title_required:'제목은 필수입니다' },
      friends: { title:'친구', my_friends:'내 친구', pending_requests:'대기 중인 요청', no_friends:'아직 친구가 없습니다', no_requests:'대기 중인 요청 없음', accept:'수락', decline:'거절', remove:'삭제', message:'메시지', friend_since:'친구가 된 날', mutual:'공통 친구', online:'온라인', offline:'오프라인', loading:'로딩 중...', view_profile:'프로필 보기', request_sent:'요청 전송됨', add_friend:'친구 추가', remove_friend:'친구 삭제', confirm_remove:'이 친구를 삭제할까요?' },
      orderDetail: { back:'주문으로 돌아가기', order_summary:'주문 요약', order_status:'주문 상태', pending:'결제 대기', payment_received:'결제 확인', shipped:'발송됨', delivered:'배달됨', cancelled:'취소됨', items_ordered:'주문 상품', seller_info:'판매자', buyer_info:'구매자', shipping_address:'배송 주소', payment_method:'결제 방법', contact_seller:'판매자 연락', contact_buyer:'구매자 연락', open_dispute:'분쟁 신청', submit_review:'리뷰 작성', track_package:'배송 추적', total:'합계', subtotal:'소계', shipping_cost:'배송비', loading:'로딩 중...', not_found:'주문을 찾을 수 없습니다', mark_shipped:'발송 완료 표시', confirm_delivery:'수령 확인', order_number:'주문', placed:'주문일', quantity:'수량' },
      geoBlock: { title:'서비스 이용 불가', subtitle:'이 서비스는 귀하의 지역에서 이용할 수 없습니다.', detected:'감지된 위치:', retry:'다시 감지', select_country:'국가 직접 선택', not_available:'귀하의 지역에서는 아직 서비스를 제공하지 않습니다.', checking:'위치 확인 중...', available_in:'이용 가능 국가' },
    }},

    de: { translation: {
      nav: { home:'Start', brand:'Ramen Anime', shop:'Shop', prints3d:'3D-Drucke', cards:'Sammelkarten', contact:'Kontakt', social:'Forum', login:'Anmelden', terms:'AGB', friends:'Freunde', profile:'Profil', marketplace:'Marktplatz', myProfile:'Mein Profil', admin:'Admin', logout:'Abmelden', menu:'Menü', language:'Sprache', donate:'Spenden' },
      hero: { title:'ラーメンアニメ', subtitle:'Ihr One-Stop-Shop für individuelle 3D-gedruckte Anime-Artikel und Sammelkarten. Mit Leidenschaft gefertigt. Mit Sorgfalt versendet.', shopNow:'Jetzt shoppen', joinCommunity:'Community beitreten' },
      features: { prints:'Individuelle 3D-Drucke', printsDesc:'Auf Bestellung gefertigte Anime-Drucke mit Premium-PLA und Resin', cards:'Sammelkarten', cardsDesc:'Pokémon, One Piece, Naruto, Dragon Ball, Yu-Gi-Oh & mehr', shipping:'Schneller Versand', shippingDesc:'Schneller Versand aller Bestellungen mit Tracking', verified:'Verifizierter Verkäufer', verifiedDesc:'Vertrauenswürdiger Verkäufer mit 100+ positiven Bewertungen' },
      products: { title:'Unsere Produkte', subtitle:'Shop-Kollektion', viewAll:'Alle Produkte ansehen', orderNow:'Jetzt bestellen', viewListing:'Im Marktplatz ansehen' },
      about: { title:'Über uns', subtitle:'Leidenschaft für Anime & Gaming', desc:'ラーメンアニメ ist ein Online-Shop eines Anime-Fans und Gamers.', customers:'Zufriedene Kunden', designs:'3D-Druck-Designs', cardsListed:'Gelistete Karten' },
      contact: { title:'Kontakt', subtitle:'In Kontakt treten', desc:'Fragen zu einer Bestellung? Individuelle 3D-Druck-Anfrage? Kontaktieren Sie uns jederzeit.', email:'E-Mail', responseTime:'Antwortzeit', shippingFrom:'Versand von', sendMessage:'Nachricht senden', name:'Name', subject:'Betreff', message:'Nachricht' },
      footer: { shop:'Shop', community:'Community', getInTouch:'Kontakt', rights:'Alle Rechte vorbehalten.' },
      ageGate: { title:'Altersnachweis erforderlich', subtitle:'Sie müssen 18 Jahre oder älter sein', desc:'Diese Website enthält Inhalte zu Sammelkarten und Anime-Merchandise.', confirm:'Ich bin 18 oder älter', exit:'Seite verlassen', readTerms:'AGB lesen', readPrivacy:'Datenschutz lesen', notice:'Mit dem Klick stimmen Sie den AGB und der Datenschutzerklärung zu.' },
      marketplace: { title:'Nutzer-Marktplatz', subtitle:'Anime-Waren kaufen & verkaufen', sellItem:'Artikel verkaufen', condition:'Zustand', price:'Preis', seller:'Verkäufer', contactSeller:'Verkäufer kontaktieren', new:'Neu', used:'Gebraucht', likeNew:'Wie neu' },
      forum: { title:'Social Forum', subtitle:'Mit Anime-Fans verbinden', newPost:'Neuer Beitrag', search:'Beiträge suchen...', category:'Kategorie', noPosts:'Noch keine Beiträge', beFirst:'Starten Sie die erste Unterhaltung!', comments:'Kommentare', likes:'Likes', views:'Aufrufe', addComment:'Kommentar hinzufügen', postComment:'Kommentar posten', sort_latest:'Neueste', sort_popular:'Beliebt', sort_pinned:'Angeheftet', load_more:'Mehr laden', start_discussion:'Diskussion starten', post_title:'Titel', post_content:'Was denken Sie?', posting:'Wird gepostet...', create_post:'Beitrag erstellen', recent_activity:'Neueste Aktivität', top_contributors:'Top-Beiträger', cat_general:'Allgemeine Diskussion', cat_general_desc:'Über alles rund um Anime und Manga reden', cat_anime:'Anime & Manga', cat_anime_desc:'Diskussionen über bestimmte Serien und Episoden', cat_gaming:'Gaming', cat_gaming_desc:'Anime-Spiele, Gacha und Gaming-Kultur', cat_trading:'Sammelkarten', cat_trading_desc:'Pokémon, One Piece, Yu-Gi-Oh und mehr', cat_3dprints:'3D-Drucke & Merch', cat_3dprints_desc:'Drucke zeigen, Techniken besprechen', cat_offtopic:'Off-Topic', cat_offtopic_desc:'Nicht-Anime-Themen und Alltag' },
      profile: { aboutMe:'Über mich', interests:'Interessen', profileSong:'Profilsong', favAnime:'Lieblings-Anime', favGames:'Lieblingsspiele', editProfile:'Profil bearbeiten', addFriend:'Freund hinzufügen', friends:'Freunde', mood:'Stimmung', location:'Ort', website:'Website', welcome:'Willkommen! Profil einrichten', createProfile:'Erstellen Sie Ihr Profil und teilen Sie es mit der Community.', notFound:'Profil nicht gefunden', noProfile:'Dieser Nutzer hat noch kein Profil eingerichtet.', setupBtn:'Profil einrichten', editBtn:'Profil bearbeiten', saveBtn:'Speichern', saving:'Wird gespeichert...', displayName:'Anzeigename', headline:'Überschrift', bio:'Über mich', recentPosts:'Neueste Beiträge', viewForum:'Forum ansehen' },
      terms: { title:'Nutzungsbedingungen', acceptRequired:'Nutzungsbedingungen erforderlich', acceptDesc:'Um auf das ラーメンアニメ Social Forum zuzugreifen, müssen Sie die Nutzungsbedingungen akzeptieren.', acceptBtn:'Ich akzeptiere die Bedingungen', readFull:'Vollständige Bedingungen lesen' },
      login: { backToHome:'Zur Startseite', welcomeBack:'Willkommen zurück', joinTitle:'ラーメンアニメ beitreten', signInDesc:'Melden Sie sich an, um auf Ihr Profil, Forum und Marktplatz zuzugreifen.', joinDesc:'Erstellen Sie ein Konto, um sich mit Anime-Fans zu verbinden.', username:'Benutzername', usernameHint:'3-30 Zeichen. Buchstaben, Zahlen und Unterstriche.', email:'E-Mail', emailHint:'Für Kontowiederherstellung erforderlich', password:'Passwort', passwordHint:'Mindestens 8 Zeichen mit Groß-/Kleinbuchstaben, Zahl und Sonderzeichen.', showPassword:'Passwort anzeigen', hidePassword:'Passwort verbergen', forgotPassword:'Passwort vergessen?', signIn:'Anmelden', createAccount:'Konto erstellen', signingIn:'Wird angemeldet...', creating:'Wird erstellt...', newHere:'Neu hier?', alreadyMember:'Bereits Mitglied?', readTerms:'AGB lesen', agreeNotice:'Mit der Registrierung stimmen Sie den AGB zu.', loginFailed:'Anmeldung fehlgeschlagen', registerFailed:'Registrierung fehlgeschlagen', welcomeToast:'Willkommen zurück!', registerToast:'Konto erstellt!', invalidPassword:'Passwort erfüllt nicht alle Anforderungen.', req1:'Mindestens 8 Zeichen', req2:'Ein Großbuchstabe', req3:'Ein Kleinbuchstabe', req4:'Eine Zahl', req5:'Ein Sonderzeichen' },
      forgotPassword: { title:'Passwort zurücksetzen', desc:'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link.', send:'Link senden', sending:'Wird gesendet...', sent:'E-Mail prüfen', sentDesc:'Falls ein Konto existiert, wurde ein Link gesendet.', backToLogin:'Zurück zum Login', emailPlaceholder:'you@example.com', requestFailed:'Anfrage fehlgeschlagen', emailLabel:'E-Mail-Adresse' },
      resetPassword: { title:'Neues Passwort festlegen', desc:'Geben Sie Ihr neues Passwort ein.', newPassword:'Neues Passwort', confirmPassword:'Passwort bestätigen', resetBtn:'Passwort zurücksetzen', resetting:'Wird zurückgesetzt...', passwordsMatch:'Passwörter stimmen nicht überein.', invalidPassword:'Passwort erfüllt nicht alle Anforderungen.', backToLogin:'Zurück zum Login', success:'Passwort aktualisiert', successDesc:'Sie können sich nun mit dem neuen Passwort anmelden.', resetFailed:'Zurücksetzen fehlgeschlagen', requestNew:'Neuen Link anfordern' },
      admin: { title:'Admin-Dashboard', overview:'Übersicht', users:'Benutzer', posts:'Beiträge', listings:'Angebote', donations:'Spenden', totalUsers:'Gesamtbenutzer', totalPosts:'Gesamtbeiträge', activeListings:'Aktive Angebote', totalDonations:'Gesamtspenden', noUsers:'Keine Benutzer', noPosts:'Keine Beiträge', noListings:'Keine Angebote', noDonations:'Noch keine Spenden', role:'Rolle', joined:'Beigetreten', actions:'Aktionen', makeAdmin:'Zum Admin machen', revokeAdmin:'Admin entziehen', delete:'Löschen', deletePost:'Beitrag löschen', deleteConfirm:'Sind Sie sicher?', approve:'Genehmigen', reject:'Ablehnen' },
      donations: { title:'ラーメンアニメ unterstützen', subtitle:'Helfen Sie der Community zu wachsen', desc:'Ihre Unterstützung hilft, Server am Laufen zu halten und neue Funktionen zu entwickeln.', payWithPayPal:'Mit PayPal spenden', sendViaRevolut:'Über Revolut senden', copyLink:'Revolut-Link kopieren', copied:'Kopiert!', recentDonors:'Neueste Unterstützer', anonymous:'Anonym', thankYou:'Vielen Dank für Ihre Unterstützung!', goal:'Ziel', raised:'Erreicht', totalDonations:'Gesamtspenden', donorCount:'Unterstützer', noDonations:'Werden Sie der erste Unterstützer!' },
      listing: { back:'Zurück', buy_now:'Jetzt kaufen', place_bid:'Gebot abgeben', current_bid:'Aktuelles Gebot', time_left:'Restzeit', instant_buy:'Sofortkauf', condition:'Zustand', seller:'Verkäufer', shipping:'Versand', ask_question:'Frage stellen', add_watchlist:'Zur Beobachtungsliste', share:'Teilen', bid_history:'Gebotshistorie', recent_bids:'Neueste Gebote', make_offer:'Angebot machen', verified_seller:'Verifizierter Verkäufer', description:'Beschreibung', similar_items:'Ähnliche Artikel', auction_ended:'Auktion beendet', quantity:'Menge', your_bid:'Ihr Gebot', min_bid:'Mindestgebot', checkout:'Zur Kasse', no_bids:'Noch keine Gebote. Seien Sie der Erste!', auction:'Auktion', fixed:'Festpreis', loading:'Wird geladen...', not_found:'Angebot nicht gefunden', ends_in:'Endet in', buy_price:'Kaufpreis', bid_now:'Jetzt bieten', contacting:'Kontaktiere...', contact_seller:'Verkäufer kontaktieren', watchlisted:'Beobachtet', watch:'Beobachten', unwatch:'Nicht mehr beobachten' },
      messages: { title:'Nachrichten', login_required:'Anmeldung erforderlich', login_to_view:'Bitte melden Sie sich an, um Nachrichten zu sehen', no_messages:'Noch keine Nachrichten', type_message:'Nachricht eingeben...', send:'Senden', conversation:'Gespräch', new_message:'Neue Nachricht', coming_soon:'Vollständige Nachrichtenfunktion kommt bald.' },
      orders: { title:'Bestellungen', my_purchases:'Meine Käufe', my_sales:'Meine Verkäufe', no_purchases:'Keine Käufe', no_sales:'Keine Verkäufe', order_number:'Bestellung #', status:'Status', total:'Gesamt', items:'Artikel', track:'Verfolgen', view_details:'Details ansehen', pending:'Ausstehend', paid:'Bezahlt', shipped:'Versendet', delivered:'Zugestellt', cancelled:'Storniert', refunded:'Erstattet', placed_on:'Bestellt am', buyer:'Käufer', seller:'Verkäufer', loading:'Wird geladen...', login_required:'Bitte anmelden, um Bestellungen zu sehen' },
      createListing: { title:'Angebot erstellen', subtitle:'Anime-Waren zum Verkauf anbieten', item_title:'Titel', item_title_ph:'z.B. Naruto Shippuden Figur - Sage Mode', description:'Beschreibung', description_ph:'Beschreiben Sie Ihren Artikel detailliert...', price:'Preis (USD)', condition:'Zustand', category:'Kategorie', images:'Fotos', listing_type:'Angebotstyp', auction:'Auktion', fixed_price:'Festpreis', duration:'Dauer', duration_7:'7 Tage', duration_14:'14 Tage', duration_30:'30 Tage', submit:'Angebot erstellen', creating:'Wird erstellt...', success:'Angebot erstellt!', error:'Fehler beim Erstellen', add_images:'Fotos hinzufügen', max_images:'Max. 10 Fotos', ai_suggest:'KI-Vorschlag', ai_analyzing:'Analysiere...', preview:'Vorschau', new:'Neu', like_new:'Wie neu', used:'Gebraucht', cat_figures:'Anime-Figuren', cat_manga:'Manga / Bücher', cat_art:'Kunst / Cels', cat_collectibles:'Sammlerstücke', cat_gaming:'Gaming', cat_cards:'Sammelkarten', cat_apparel:'Bekleidung', cat_accessories:'Zubehör', cat_3d:'3D-Drucke', cat_other:'Sonstiges', login_required:'Bitte anmelden, um ein Angebot zu erstellen', min_images:'Fügen Sie mindestens ein Foto hinzu', min_price:'Preis muss mindestens $0,01 sein', title_required:'Titel ist erforderlich' },
      friends: { title:'Freunde', my_friends:'Meine Freunde', pending_requests:'Ausstehende Anfragen', no_friends:'Noch keine Freunde', no_requests:'Keine ausstehenden Anfragen', accept:'Annehmen', decline:'Ablehnen', remove:'Entfernen', message:'Nachricht', friend_since:'Freunde seit', mutual:'gemeinsame Freunde', online:'Online', offline:'Offline', loading:'Wird geladen...', view_profile:'Profil ansehen', request_sent:'Anfrage gesendet', add_friend:'Freund hinzufügen', remove_friend:'Freund entfernen', confirm_remove:'Freund entfernen?' },
      orderDetail: { back:'Zurück zu Bestellungen', order_summary:'Bestellübersicht', order_status:'Bestellstatus', pending:'Zahlung ausstehend', payment_received:'Zahlung eingegangen', shipped:'Versendet', delivered:'Zugestellt', cancelled:'Storniert', items_ordered:'Bestellte Artikel', seller_info:'Verkäufer', buyer_info:'Käufer', shipping_address:'Lieferadresse', payment_method:'Zahlungsmethode', contact_seller:'Verkäufer kontaktieren', contact_buyer:'Käufer kontaktieren', open_dispute:'Streitfall eröffnen', submit_review:'Bewertung abgeben', track_package:'Paket verfolgen', total:'Gesamt', subtotal:'Zwischensumme', shipping_cost:'Versandkosten', loading:'Wird geladen...', not_found:'Bestellung nicht gefunden', mark_shipped:'Als versendet markieren', confirm_delivery:'Lieferung bestätigen', order_number:'Bestellung', placed:'Aufgegeben', quantity:'Menge' },
      geoBlock: { title:'Dienst nicht verfügbar', subtitle:'Dieser Dienst ist in Ihrer Region nicht verfügbar.', detected:'Erkannt:', retry:'Erneut erkennen', select_country:'Land manuell auswählen', not_available:'In Ihrer Region bieten wir derzeit keine Dienste an.', checking:'Standort wird geprüft...', available_in:'Verfügbare Länder' },
    }},

    fr: { translation: {
      nav: { home:'Accueil', brand:'Ramen Anime', shop:'Boutique', prints3d:'Impressions 3D', cards:'Cartes', contact:'Contact', social:'Forum', login:'Connexion', terms:'CGU', friends:'Amis', profile:'Profil', marketplace:'Marché', myProfile:'Mon Profil', admin:'Admin', logout:'Déconnexion', menu:'Menu', language:'Langue', donate:'Faire un don' },
      hero: { title:'ラーメンアニメ', subtitle:'Votre boutique unique pour des articles anime imprimés en 3D et des cartes à collectionner. Fabriqué avec passion. Expédié avec soin.', shopNow:'Acheter maintenant', joinCommunity:'Rejoindre la communauté' },
      features: { prints:'Impressions 3D personnalisées', printsDesc:'Impressions anime sur commande avec PLA et résine premium', cards:'Cartes à collectionner', cardsDesc:'Pokémon, One Piece, Naruto, Dragon Ball, Yu-Gi-Oh & plus', shipping:'Expédition rapide', shippingDesc:'Expédition rapide avec suivi', verified:'Vendeur vérifié', verifiedDesc:'Vendeur de confiance avec 100+ avis positifs' },
      products: { title:'Nos produits', subtitle:'Collection boutique', viewAll:'Voir tous les produits', orderNow:'Commander', viewListing:'Voir sur le marché' },
      about: { title:'À propos', subtitle:"Passion pour l'anime et le gaming", desc:"ラーメンアニメ est une boutique en ligne gérée par un fan d'anime.", customers:'Clients satisfaits', designs:'Designs 3D', cardsListed:'Cartes listées' },
      contact: { title:'Nous contacter', subtitle:'Entrer en contact', desc:"Des questions sur une commande? Une demande d'impression 3D? Contactez-nous à tout moment.", email:'Email', responseTime:'Temps de réponse', shippingFrom:'Expédié depuis', sendMessage:'Envoyer un message', name:'Nom', subject:'Sujet', message:'Message' },
      footer: { shop:'Boutique', community:'Communauté', getInTouch:'Contact', rights:'Tous droits réservés.' },
      ageGate: { title:"Vérification d'âge requise", subtitle:'Vous devez avoir 18 ans ou plus', desc:'Ce site contient du contenu lié aux cartes à collectionner et aux produits anime.', confirm:"J'ai 18 ans ou plus", exit:'Quitter le site', readTerms:'Lire les CGU', readPrivacy:'Lire la politique de confidentialité', notice:'En cliquant, vous acceptez les CGU et la politique de confidentialité.' },
      marketplace: { title:'Marché utilisateurs', subtitle:'Acheter et vendre des articles anime', sellItem:'Vendre un article', condition:'État', price:'Prix', seller:'Vendeur', contactSeller:'Contacter le vendeur', new:'Neuf', used:'Occasion', likeNew:'Comme neuf' },
      forum: { title:'Forum social', subtitle:"Connectez-vous avec des fans d'anime", newPost:'Nouveau message', search:'Rechercher...', category:'Catégorie', noPosts:'Aucun message', beFirst:'Soyez le premier à démarrer une conversation!', comments:'Commentaires', likes:"J'aime", views:'Vues', addComment:'Ajouter un commentaire', postComment:'Publier', sort_latest:'Récents', sort_popular:'Populaires', sort_pinned:'Épinglés', load_more:'Charger plus', start_discussion:'Démarrer une discussion', post_title:'Titre', post_content:"Qu'avez-vous en tête?", posting:'Publication...', create_post:'Créer', recent_activity:'Activité récente', top_contributors:'Meilleurs contributeurs', cat_general:'Discussion générale', cat_general_desc:"Parlez de tout ce qui concerne l'anime", cat_anime:'Anime & Manga', cat_anime_desc:'Discussions sur des séries et épisodes', cat_gaming:'Gaming', cat_gaming_desc:'Jeux anime, gacha et culture gaming', cat_trading:'Cartes', cat_trading_desc:'Pokémon, One Piece, Yu-Gi-Oh et plus', cat_3dprints:'Impressions 3D', cat_3dprints_desc:'Montrez vos impressions et partagez des boutiques', cat_offtopic:'Hors-sujet', cat_offtopic_desc:'Sujets non-anime et vie quotidienne' },
      profile: { aboutMe:'À propos de moi', interests:'Intérêts', profileSong:'Chanson de profil', favAnime:'Anime préféré', favGames:'Jeux préférés', editProfile:'Modifier le profil', addFriend:'Ajouter un ami', friends:'Amis', mood:'Humeur', location:'Lieu', website:'Site web', welcome:'Bienvenue! Configurez votre profil', createProfile:'Créez votre profil et partagez-le avec la communauté.', notFound:'Profil introuvable', noProfile:"Cet utilisateur n'a pas encore configuré son profil.", setupBtn:'Configurer le profil', editBtn:'Modifier', saveBtn:'Enregistrer', saving:'Enregistrement...', displayName:"Nom d'affichage", headline:'Titre', bio:'À propos de moi', recentPosts:'Messages récents', viewForum:'Voir le forum' },
      terms: { title:"Conditions d'utilisation", acceptRequired:'Conditions requises', acceptDesc:"Avant d'accéder au forum ラーメンアニメ, lisez et acceptez les conditions.", acceptBtn:"J'accepte les conditions", readFull:'Lire les conditions complètes' },
      login: { backToHome:"Retour à l'accueil", welcomeBack:'Bon retour', joinTitle:'Rejoindre ラーメンアニメ', signInDesc:'Connectez-vous pour accéder à votre profil, forum et marché.', joinDesc:"Créez un compte pour vous connecter avec des fans d'anime.", username:"Nom d'utilisateur", usernameHint:'3-30 caractères. Lettres, chiffres et underscores.', email:'Email', emailHint:'Requis pour la récupération de compte', password:'Mot de passe', passwordHint:'8 caractères minimum avec majuscule, minuscule, chiffre et caractère spécial.', showPassword:'Afficher', hidePassword:'Masquer', forgotPassword:'Mot de passe oublié?', signIn:'Se connecter', createAccount:'Créer un compte', signingIn:'Connexion...', creating:'Création...', newHere:'Nouveau ici?', alreadyMember:'Déjà membre?', readTerms:'Lire les CGU', agreeNotice:'En vous inscrivant, vous acceptez les CGU.', loginFailed:'Connexion échouée', registerFailed:'Inscription échouée', welcomeToast:'Bon retour!', registerToast:'Compte créé!', invalidPassword:'Le mot de passe ne satisfait pas toutes les exigences.', req1:'Au moins 8 caractères', req2:'Une majuscule', req3:'Une minuscule', req4:'Un chiffre', req5:'Un caractère spécial' },
      forgotPassword: { title:'Réinitialiser le mot de passe', desc:'Entrez votre email et nous vous enverrons un lien.', send:'Envoyer le lien', sending:'Envoi...', sent:'Vérifiez votre email', sentDesc:'Si un compte existe, un lien a été envoyé.', backToLogin:'Retour à la connexion', emailPlaceholder:'you@example.com', requestFailed:'Demande échouée', emailLabel:'Adresse email' },
      resetPassword: { title:'Nouveau mot de passe', desc:'Entrez votre nouveau mot de passe.', newPassword:'Nouveau mot de passe', confirmPassword:'Confirmer', resetBtn:'Réinitialiser', resetting:'Réinitialisation...', passwordsMatch:'Les mots de passe ne correspondent pas.', invalidPassword:'Mot de passe invalide.', backToLogin:'Retour connexion', success:'Mot de passe mis à jour', successDesc:'Vous pouvez maintenant vous connecter.', resetFailed:'Échec', requestNew:'Demander un nouveau lien' },
      admin: { title:'Tableau de bord admin', overview:"Vue d'ensemble", users:'Utilisateurs', posts:'Messages', listings:'Annonces', donations:'Dons', totalUsers:'Total utilisateurs', totalPosts:'Total messages', activeListings:'Annonces actives', totalDonations:'Total dons', noUsers:'Aucun utilisateur', noPosts:'Aucun message', noListings:'Aucune annonce', noDonations:'Pas encore de dons', role:'Rôle', joined:'Inscrit', actions:'Actions', makeAdmin:'Rendre admin', revokeAdmin:'Révoquer admin', delete:'Supprimer', deletePost:'Supprimer le message', deleteConfirm:'Êtes-vous sûr?', approve:'Approuver', reject:'Rejeter' },
      donations: { title:'Soutenir ラーメンアニメ', subtitle:'Aidez la communauté à grandir', desc:'Votre soutien aide à maintenir les serveurs et développer de nouvelles fonctionnalités.', payWithPayPal:'Faire un don via PayPal', sendViaRevolut:'Envoyer via Revolut', copyLink:'Copier le lien Revolut', copied:'Copié!', recentDonors:'Derniers soutiens', anonymous:'Anonyme', thankYou:'Merci pour votre soutien!', goal:'Objectif', raised:'Collecté', totalDonations:'Total collecté', donorCount:'Soutiens', noDonations:'Soyez le premier à soutenir!' },
      listing: { back:'Retour', buy_now:'Acheter maintenant', place_bid:'Enchérir', current_bid:'Enchère actuelle', time_left:'Temps restant', instant_buy:'Achat immédiat', condition:'État', seller:'Vendeur', shipping:'Livraison', ask_question:'Poser une question', add_watchlist:'Ajouter aux favoris', share:'Partager', bid_history:'Historique des enchères', recent_bids:'Enchères récentes', make_offer:'Faire une offre', verified_seller:'Vendeur vérifié', description:'Description', similar_items:'Articles similaires', auction_ended:'Vente terminée', quantity:'Quantité', your_bid:'Votre enchère', min_bid:'Enchère minimale', checkout:'Passer à la caisse', no_bids:"Pas encore d'enchères. Soyez le premier!", auction:'Enchère', fixed:'Prix fixe', loading:'Chargement...', not_found:'Annonce introuvable', ends_in:'Se termine dans', buy_price:"Prix d'achat", bid_now:'Enchérir maintenant', contacting:'Contact...', contact_seller:'Contacter le vendeur', watchlisted:'En favoris', watch:'Suivre', unwatch:'Ne plus suivre' },
      messages: { title:'Messages', login_required:'Connexion requise', login_to_view:'Connectez-vous pour voir vos messages', no_messages:'Aucun message', type_message:'Tapez un message...', send:'Envoyer', conversation:'Conversation', new_message:'Nouveau message', coming_soon:'Messagerie complète bientôt disponible.' },
      orders: { title:'Commandes', my_purchases:'Mes achats', my_sales:'Mes ventes', no_purchases:'Aucun achat', no_sales:'Aucune vente', order_number:'Commande #', status:'Statut', total:'Total', items:'Articles', track:'Suivre', view_details:'Voir les détails', pending:'En attente', paid:'Payé', shipped:'Expédié', delivered:'Livré', cancelled:'Annulé', refunded:'Remboursé', placed_on:'Passé le', buyer:'Acheteur', seller:'Vendeur', loading:'Chargement...', login_required:'Connectez-vous pour voir vos commandes' },
      createListing: { title:'Créer une annonce', subtitle:'Mettez vos articles anime en vente', item_title:'Titre', item_title_ph:'ex: Figurine Naruto Shippuden - Mode Sage', description:'Description', description_ph:'Décrivez votre article en détail...', price:'Prix (USD)', condition:'État', category:'Catégorie', images:'Photos', listing_type:"Type d'annonce", auction:'Enchère', fixed_price:'Prix fixe', duration:'Durée', duration_7:'7 jours', duration_14:'14 jours', duration_30:'30 jours', submit:'Mettre en vente', creating:'Création...', success:'Annonce créée!', error:'Échec de création', add_images:'Ajouter des photos', max_images:'Max 10 photos', ai_suggest:'Suggestion IA', ai_analyzing:'Analyse...', preview:'Aperçu', new:'Neuf', like_new:'Comme neuf', used:'Occasion', cat_figures:'Figurines anime', cat_manga:'Manga / Livres', cat_art:'Art / Cels', cat_collectibles:'Objets de collection', cat_gaming:'Gaming', cat_cards:'Cartes', cat_apparel:'Vêtements', cat_accessories:'Accessoires', cat_3d:'Impressions 3D', cat_other:'Autre', login_required:'Connectez-vous pour créer une annonce', min_images:'Ajoutez au moins une photo', min_price:"Le prix doit être d'au moins $0.01", title_required:'Le titre est requis' },
      friends: { title:'Amis', my_friends:'Mes amis', pending_requests:'Demandes en attente', no_friends:"Pas encore d'amis", no_requests:'Aucune demande en attente', accept:'Accepter', decline:'Refuser', remove:'Supprimer', message:'Message', friend_since:'Amis depuis', mutual:'amis en commun', online:'En ligne', offline:'Hors ligne', loading:'Chargement...', view_profile:'Voir le profil', request_sent:'Demande envoyée', add_friend:'Ajouter un ami', remove_friend:"Supprimer l'ami", confirm_remove:'Supprimer cet ami?' },
      orderDetail: { back:'Retour aux commandes', order_summary:'Résumé de commande', order_status:'Statut', pending:'En attente de paiement', payment_received:'Paiement reçu', shipped:'Expédié', delivered:'Livré', cancelled:'Annulé', items_ordered:'Articles commandés', seller_info:'Vendeur', buyer_info:'Acheteur', shipping_address:'Adresse de livraison', payment_method:'Paiement', contact_seller:'Contacter le vendeur', contact_buyer:"Contacter l'acheteur", open_dispute:'Ouvrir un litige', submit_review:'Laisser un avis', track_package:'Suivre le colis', total:'Total', subtotal:'Sous-total', shipping_cost:'Livraison', loading:'Chargement...', not_found:'Commande introuvable', mark_shipped:'Marquer comme expédié', confirm_delivery:'Confirmer la livraison', order_number:'Commande', placed:'Passé', quantity:'Qté' },
      geoBlock: { title:'Service non disponible', subtitle:"Ce service n'est pas disponible dans votre région.", detected:'Détecté:', retry:'Réessayer', select_country:'Choisir le pays manuellement', not_available:'Nous ne sommes pas encore disponibles dans votre région.', checking:'Vérification de votre position...', available_in:'Pays disponibles' },
    }},

    es: { translation: {
      nav: { home:'Inicio', brand:'Ramen Anime', shop:'Tienda', prints3d:'Impresiones 3D', cards:'Cartas', contact:'Contacto', social:'Foro', login:'Entrar', terms:'Términos', friends:'Amigos', profile:'Perfil', marketplace:'Mercado', myProfile:'Mi Perfil', admin:'Admin', logout:'Cerrar sesión', menu:'Menú', language:'Idioma', donate:'Donar' },
      hero: { title:'ラーメンアニメ', subtitle:'Tu tienda única para artículos anime impresos en 3D y cartas coleccionables. Hecho con pasión. Enviado con cuidado.', shopNow:'Comprar ahora', joinCommunity:'Unirse a la comunidad' },
      features: { prints:'Impresiones 3D personalizadas', printsDesc:'Impresiones anime temáticas hechas a pedido con PLA y resina premium', cards:'Cartas coleccionables', cardsDesc:'Pokémon, One Piece, Naruto, Dragon Ball, Yu-Gi-Oh y más', shipping:'Envío rápido', shippingDesc:'Envío rápido en todos los pedidos con seguimiento', verified:'Vendedor verificado', verifiedDesc:'Vendedor de confianza con más de 100 reseñas positivas' },
      products: { title:'Nuestros productos', subtitle:'Colección de la tienda', viewAll:'Ver todos los productos', orderNow:'Pedir ahora', viewListing:'Ver en el mercado' },
      about: { title:'Sobre nosotros', subtitle:'Pasión por el anime y los juegos', desc:'ラーメンアニメ es una tienda online gestionada por un fan del anime.', customers:'Clientes felices', designs:'Diseños 3D', cardsListed:'Cartas listadas' },
      contact: { title:'Contáctanos', subtitle:'Ponte en contacto', desc:'¿Preguntas sobre un pedido? ¿Solicitud de impresión 3D? Escríbenos cuando quieras.', email:'Email', responseTime:'Tiempo de respuesta', shippingFrom:'Envío desde', sendMessage:'Enviar mensaje', name:'Nombre', subject:'Asunto', message:'Mensaje' },
      footer: { shop:'Tienda', community:'Comunidad', getInTouch:'Contacto', rights:'Todos los derechos reservados.' },
      ageGate: { title:'Verificación de edad requerida', subtitle:'Debes tener 18 años o más para entrar', desc:'Este sitio contiene contenido relacionado con cartas coleccionables y merchandise anime.', confirm:'Tengo 18 años o más', exit:'Salir del sitio', readTerms:'Leer Términos de Servicio', readPrivacy:'Leer Política de Privacidad', notice:'Al hacer clic, aceptas los Términos y la Política de Privacidad.' },
      marketplace: { title:'Mercado de usuarios', subtitle:'Compra y vende artículos anime', sellItem:'Vender un artículo', condition:'Condición', price:'Precio', seller:'Vendedor', contactSeller:'Contactar vendedor', new:'Nuevo', used:'Usado', likeNew:'Como nuevo' },
      forum: { title:'Foro social', subtitle:'Conecta con fans del anime', newPost:'Nueva publicación', search:'Buscar publicaciones...', category:'Categoría', noPosts:'Sin publicaciones aún', beFirst:'¡Sé el primero en iniciar una conversación!', comments:'Comentarios', likes:'Me gusta', views:'Vistas', addComment:'Añadir comentario', postComment:'Publicar comentario', sort_latest:'Recientes', sort_popular:'Populares', sort_pinned:'Fijados', load_more:'Cargar más', start_discussion:'Iniciar debate', post_title:'Título', post_content:'¿Qué estás pensando?', posting:'Publicando...', create_post:'Crear publicación', recent_activity:'Actividad reciente', top_contributors:'Mejores contribuidores', cat_general:'Discusión general', cat_general_desc:'Habla sobre anime y manga', cat_anime:'Anime & Manga', cat_anime_desc:'Discusiones sobre series y episodios', cat_gaming:'Gaming', cat_gaming_desc:'Juegos anime, gacha y cultura gaming', cat_trading:'Cartas coleccionables', cat_trading_desc:'Pokémon, One Piece, Yu-Gi-Oh y más', cat_3dprints:'Impresiones 3D', cat_3dprints_desc:'Muestra tus impresiones y comparte tiendas', cat_offtopic:'Fuera de tema', cat_offtopic_desc:'Temas no relacionados con anime' },
      profile: { aboutMe:'Sobre mí', interests:'Intereses', profileSong:'Canción de perfil', favAnime:'Anime favorito', favGames:'Juegos favoritos', editProfile:'Editar perfil', addFriend:'Añadir amigo', friends:'Amigos', mood:'Estado de ánimo', location:'Ubicación', website:'Sitio web', welcome:'¡Bienvenido! Configura tu perfil', createProfile:'Crea tu perfil y compártelo con la comunidad.', notFound:'Perfil no encontrado', noProfile:'Este usuario aún no ha configurado su perfil.', setupBtn:'Configurar perfil', editBtn:'Editar perfil', saveBtn:'Guardar', saving:'Guardando...', displayName:'Nombre visible', headline:'Título', bio:'Sobre mí', recentPosts:'Publicaciones recientes', viewForum:'Ver foro' },
      terms: { title:'Términos de servicio', acceptRequired:'Se requieren los Términos de Servicio', acceptDesc:'Antes de acceder al foro de ラーメンアニメ, lee y acepta los Términos de Servicio.', acceptBtn:'Acepto los términos', readFull:'Leer términos completos' },
      login: { backToHome:'Volver al inicio', welcomeBack:'Bienvenido de vuelta', joinTitle:'Unirse a ラーメンアニメ', signInDesc:'Inicia sesión para acceder a tu perfil, foro y mercado.', joinDesc:'Crea una cuenta para conectarte con fans del anime.', username:'Usuario', usernameHint:'3-30 caracteres. Letras, números y guiones bajos.', email:'Email', emailHint:'Requerido para recuperación de cuenta', password:'Contraseña', passwordHint:'Mínimo 8 caracteres con mayúscula, minúscula, número y carácter especial.', showPassword:'Mostrar', hidePassword:'Ocultar', forgotPassword:'¿Olvidaste tu contraseña?', signIn:'Iniciar sesión', createAccount:'Crear cuenta', signingIn:'Iniciando sesión...', creating:'Creando...', newHere:'¿Nuevo aquí?', alreadyMember:'¿Ya eres miembro?', readTerms:'Leer Términos', agreeNotice:'Al registrarte, aceptas los Términos de Servicio.', loginFailed:'Error al iniciar sesión', registerFailed:'Error al registrarse', welcomeToast:'¡Bienvenido de vuelta!', registerToast:'¡Cuenta creada!', invalidPassword:'La contraseña no cumple todos los requisitos.', req1:'Al menos 8 caracteres', req2:'Una letra mayúscula', req3:'Una letra minúscula', req4:'Un número', req5:'Un carácter especial' },
      forgotPassword: { title:'Restablecer contraseña', desc:'Ingresa tu email y te enviaremos un enlace.', send:'Enviar enlace', sending:'Enviando...', sent:'Revisa tu email', sentDesc:'Si existe una cuenta, se ha enviado un enlace de restablecimiento.', backToLogin:'Volver al inicio de sesión', emailPlaceholder:'tu@email.com', requestFailed:'Solicitud fallida', emailLabel:'Dirección de email' },
      resetPassword: { title:'Nueva contraseña', desc:'Ingresa tu nueva contraseña.', newPassword:'Nueva contraseña', confirmPassword:'Confirmar', resetBtn:'Restablecer', resetting:'Restableciendo...', passwordsMatch:'Las contraseñas no coinciden.', invalidPassword:'Contraseña inválida.', backToLogin:'Volver', success:'Contraseña actualizada', successDesc:'Ya puedes iniciar sesión.', resetFailed:'Error', requestNew:'Solicitar nuevo enlace' },
      admin: { title:'Panel de administración', overview:'Resumen', users:'Usuarios', posts:'Publicaciones', listings:'Anuncios', donations:'Donaciones', totalUsers:'Total usuarios', totalPosts:'Total publicaciones', activeListings:'Anuncios activos', totalDonations:'Total donaciones', noUsers:'Sin usuarios', noPosts:'Sin publicaciones', noListings:'Sin anuncios', noDonations:'Aún no hay donaciones', role:'Rol', joined:'Registrado', actions:'Acciones', makeAdmin:'Hacer admin', revokeAdmin:'Revocar admin', delete:'Eliminar', deletePost:'Eliminar publicación', deleteConfirm:'¿Estás seguro?', approve:'Aprobar', reject:'Rechazar' },
      donations: { title:'Apoyar ラーメンアニメ', subtitle:'Ayuda a crecer a la comunidad', desc:'Tu apoyo ayuda a mantener los servidores y desarrollar nuevas funciones.', payWithPayPal:'Donar con PayPal', sendViaRevolut:'Enviar via Revolut', copyLink:'Copiar enlace Revolut', copied:'¡Copiado!', recentDonors:'Últimos colaboradores', anonymous:'Anónimo', thankYou:'¡Gracias por tu apoyo!', goal:'Objetivo', raised:'Recaudado', totalDonations:'Total recaudado', donorCount:'Colaboradores', noDonations:'¡Sé el primero en colaborar!' },
      listing: { back:'Volver', buy_now:'Comprar ahora', place_bid:'Pujar', current_bid:'Puja actual', time_left:'Tiempo restante', instant_buy:'Compra inmediata', condition:'Condición', seller:'Vendedor', shipping:'Envío', ask_question:'Hacer una pregunta', add_watchlist:'Añadir a favoritos', share:'Compartir', bid_history:'Historial de pujas', recent_bids:'Pujas recientes', make_offer:'Hacer oferta', verified_seller:'Vendedor verificado', description:'Descripción', similar_items:'Artículos similares', auction_ended:'Subasta finalizada', quantity:'Cantidad', your_bid:'Tu puja', min_bid:'Puja mínima', checkout:'Pagar', no_bids:'Sin pujas aún. ¡Sé el primero!', auction:'Subasta', fixed:'Precio fijo', loading:'Cargando...', not_found:'Anuncio no encontrado', ends_in:'Termina en', buy_price:'Precio de compra', bid_now:'Pujar ahora', contacting:'Contactando...', contact_seller:'Contactar vendedor', watchlisted:'En favoritos', watch:'Seguir', unwatch:'Dejar de seguir' },
      messages: { title:'Mensajes', login_required:'Inicio de sesión requerido', login_to_view:'Inicia sesión para ver tus mensajes', no_messages:'Sin mensajes', type_message:'Escribe un mensaje...', send:'Enviar', conversation:'Conversación', new_message:'Nuevo mensaje', coming_soon:'Mensajería completa próximamente.' },
      orders: { title:'Pedidos', my_purchases:'Mis compras', my_sales:'Mis ventas', no_purchases:'Sin compras', no_sales:'Sin ventas', order_number:'Pedido #', status:'Estado', total:'Total', items:'Artículos', track:'Rastrear', view_details:'Ver detalles', pending:'Pendiente', paid:'Pagado', shipped:'Enviado', delivered:'Entregado', cancelled:'Cancelado', refunded:'Reembolsado', placed_on:'Realizado el', buyer:'Comprador', seller:'Vendedor', loading:'Cargando...', login_required:'Inicia sesión para ver tus pedidos' },
      createListing: { title:'Crear anuncio', subtitle:'Pon tus artículos anime a la venta', item_title:'Título', item_title_ph:'ej: Figura Naruto Shippuden - Modo Sabio', description:'Descripción', description_ph:'Describe tu artículo detalladamente...', price:'Precio (USD)', condition:'Condición', category:'Categoría', images:'Fotos', listing_type:'Tipo de anuncio', auction:'Subasta', fixed_price:'Precio fijo', duration:'Duración', duration_7:'7 días', duration_14:'14 días', duration_30:'30 días', submit:'Publicar', creating:'Publicando...', success:'¡Anuncio creado!', error:'Error al crear', add_images:'Añadir fotos', max_images:'Máx 10 fotos', ai_suggest:'Sugerencia IA', ai_analyzing:'Analizando...', preview:'Vista previa', new:'Nuevo', like_new:'Como nuevo', used:'Usado', cat_figures:'Figuras anime', cat_manga:'Manga / Libros', cat_art:'Arte / Cels', cat_collectibles:'Coleccionables', cat_gaming:'Gaming', cat_cards:'Cartas', cat_apparel:'Ropa', cat_accessories:'Accesorios', cat_3d:'Impresiones 3D', cat_other:'Otro', login_required:'Inicia sesión para crear un anuncio', min_images:'Añade al menos una foto', min_price:'El precio debe ser al menos $0.01', title_required:'El título es requerido' },
      friends: { title:'Amigos', my_friends:'Mis amigos', pending_requests:'Solicitudes pendientes', no_friends:'Sin amigos aún', no_requests:'Sin solicitudes pendientes', accept:'Aceptar', decline:'Rechazar', remove:'Eliminar', message:'Mensaje', friend_since:'Amigos desde', mutual:'amigos en común', online:'En línea', offline:'Desconectado', loading:'Cargando...', view_profile:'Ver perfil', request_sent:'Solicitud enviada', add_friend:'Añadir amigo', remove_friend:'Eliminar amigo', confirm_remove:'¿Eliminar este amigo?' },
      orderDetail: { back:'Volver a pedidos', order_summary:'Resumen del pedido', order_status:'Estado del pedido', pending:'Pago pendiente', payment_received:'Pago recibido', shipped:'Enviado', delivered:'Entregado', cancelled:'Cancelado', items_ordered:'Artículos pedidos', seller_info:'Vendedor', buyer_info:'Comprador', shipping_address:'Dirección de envío', payment_method:'Pago', contact_seller:'Contactar vendedor', contact_buyer:'Contactar comprador', open_dispute:'Abrir disputa', submit_review:'Dejar reseña', track_package:'Rastrear paquete', total:'Total', subtotal:'Subtotal', shipping_cost:'Envío', loading:'Cargando...', not_found:'Pedido no encontrado', mark_shipped:'Marcar como enviado', confirm_delivery:'Confirmar entrega', order_number:'Pedido', placed:'Realizado', quantity:'Cant.' },
      geoBlock: { title:'Servicio no disponible', subtitle:'Este servicio no está disponible en tu región.', detected:'Detectado:', retry:'Reintentar detección', select_country:'Seleccionar país manualmente', not_available:'Aún no estamos disponibles en tu región.', checking:'Verificando tu ubicación...', available_in:'Países disponibles' },
    }},

    'zh-CN': { translation: {
      nav: { home:'首页', brand:'Ramen Anime', shop:'商店', prints3d:'3D打印', cards:'卡牌', contact:'联系', social:'社区', login:'登录', terms:'条款', friends:'好友', profile:'档案', marketplace:'市场', myProfile:'我的档案', admin:'管理', logout:'退出', menu:'菜单', language:'语言', donate:'捐赠' },
      hero: { title:'ラーメンアニメ', subtitle:'您一站式的动漫3D打印商品和卡牌收藏店。用心制作，用心发货。', shopNow:'立即购买', joinCommunity:'加入社区' },
      features: { prints:'定制3D打印', printsDesc:'使用优质PLA和树脂按订单制作的动漫主题打印品', cards:'卡牌收藏', cardsDesc:'口袋妖怪、海贼王、火影忍者、龙珠、游戏王等', shipping:'快速发货', shippingDesc:'所有订单快速发货，提供追踪服务', verified:'认证卖家', verifiedDesc:'拥有100+好评的信赖卖家' },
      products: { title:'我们的商品', subtitle:'商店系列', viewAll:'查看所有商品', orderNow:'立即订购', viewListing:'在市场查看' },
      about: { title:'关于我们', subtitle:'对动漫与游戏的热情', desc:'ラーメンアニメ是由动漫爱好者经营的网络商店。', customers:'满意客户', designs:'3D打印设计', cardsListed:'上架卡牌' },
      contact: { title:'联系我们', subtitle:'取得联系', desc:'对订单有疑问？定制3D打印请求？随时联系我们。', email:'邮箱', responseTime:'回复时间', shippingFrom:'发货地', sendMessage:'发送消息', name:'姓名', subject:'主题', message:'消息' },
      footer: { shop:'商店', community:'社区', getInTouch:'联系我们', rights:'版权所有。' },
      ageGate: { title:'需要年龄验证', subtitle:'您必须年满18岁才能进入', desc:'本网站包含与收藏卡牌和动漫商品相关的内容。', confirm:'我已满18岁', exit:'离开网站', readTerms:'阅读服务条款', readPrivacy:'阅读隐私政策', notice:'点击即表示您同意服务条款和隐私政策。' },
      marketplace: { title:'用户市场', subtitle:'买卖动漫商品', sellItem:'出售物品', condition:'状况', price:'价格', seller:'卖家', contactSeller:'联系卖家', new:'全新', used:'二手', likeNew:'近全新' },
      forum: { title:'社交论坛', subtitle:'与动漫爱好者交流', newPost:'发帖', search:'搜索帖子...', category:'分类', noPosts:'暂无帖子', beFirst:'成为第一个开始对话的人！', comments:'评论', likes:'点赞', views:'浏览', addComment:'添加评论', postComment:'发表评论', sort_latest:'最新', sort_popular:'热门', sort_pinned:'置顶', load_more:'加载更多', start_discussion:'开始讨论', post_title:'标题', post_content:'你在想什么？', posting:'发布中...', create_post:'发布', recent_activity:'最近活动', top_contributors:'最佳贡献者', cat_general:'综合讨论', cat_general_desc:'聊聊动漫和漫画相关的任何话题', cat_anime:'动漫 & 漫画', cat_anime_desc:'关于具体系列、剧集和章节的讨论', cat_gaming:'游戏', cat_gaming_desc:'动漫游戏、抽卡游戏和游戏文化', cat_trading:'集换卡牌', cat_trading_desc:'口袋妖怪、海贼王、游戏王等', cat_3dprints:'3D打印 & 周边', cat_3dprints_desc:'展示你的打印品，分享技巧', cat_offtopic:'其他话题', cat_offtopic_desc:'非动漫话题和日常生活' },
      profile: { aboutMe:'关于我', interests:'兴趣', profileSong:'主题曲', favAnime:'最爱动漫', favGames:'最爱游戏', editProfile:'编辑档案', addFriend:'添加好友', friends:'好友', mood:'心情', location:'位置', website:'网站', welcome:'欢迎！设置您的档案', createProfile:'创建您的档案并与社区分享。', notFound:'找不到档案', noProfile:'该用户尚未设置档案。', setupBtn:'设置档案', editBtn:'编辑档案', saveBtn:'保存', saving:'保存中...', displayName:'显示名称', headline:'简介标题', bio:'关于我', recentPosts:'最近帖子', viewForum:'查看论坛' },
      terms: { title:'服务条款', acceptRequired:'需要接受服务条款', acceptDesc:'访问ラーメンアニメ社区论坛前，请阅读并接受服务条款。', acceptBtn:'我接受条款', readFull:'阅读完整条款' },
      login: { backToHome:'返回主页', welcomeBack:'欢迎回来', joinTitle:'加入ラーメンアニメ', signInDesc:'登录访问您的档案、论坛和市场。', joinDesc:'创建账户与动漫爱好者连接。', username:'用户名', usernameHint:'3-30个字符，仅限字母、数字和下划线。', email:'邮箱', emailHint:'账户恢复所需', password:'密码', passwordHint:'至少8个字符，含大写、小写、数字和特殊字符。', showPassword:'显示密码', hidePassword:'隐藏密码', forgotPassword:'忘记密码？', signIn:'登录', createAccount:'创建账户', signingIn:'登录中...', creating:'创建中...', newHere:'新用户？', alreadyMember:'已有账户？', readTerms:'阅读服务条款', agreeNotice:'注册或登录即表示同意服务条款。', loginFailed:'登录失败', registerFailed:'注册失败', welcomeToast:'欢迎回来！', registerToast:'账户已创建！', invalidPassword:'密码不符合要求。', req1:'至少8个字符', req2:'一个大写字母', req3:'一个小写字母', req4:'一个数字', req5:'一个特殊字符' },
      forgotPassword: { title:'重置密码', desc:'输入您的邮箱，我们将发送重置链接。', send:'发送重置链接', sending:'发送中...', sent:'检查您的邮箱', sentDesc:'如果账户存在，我们已发送密码重置链接。', backToLogin:'返回登录', emailPlaceholder:'your@email.com', requestFailed:'请求失败', emailLabel:'邮箱地址' },
      resetPassword: { title:'设置新密码', desc:'请输入新密码。', newPassword:'新密码', confirmPassword:'确认密码', resetBtn:'重置密码', resetting:'重置中...', passwordsMatch:'密码不匹配。', invalidPassword:'密码不符合要求。', backToLogin:'返回登录', success:'密码已更新', successDesc:'您现在可以用新密码登录。', resetFailed:'重置失败', requestNew:'请求新链接' },
      admin: { title:'管理员控制台', overview:'概览', users:'用户', posts:'帖子', listings:'商品', donations:'捐赠', totalUsers:'总用户', totalPosts:'总帖子', activeListings:'活跃商品', totalDonations:'总捐赠', noUsers:'无用户', noPosts:'无帖子', noListings:'无商品', noDonations:'暂无捐赠', role:'角色', joined:'加入时间', actions:'操作', makeAdmin:'设为管理员', revokeAdmin:'撤销管理员', delete:'删除', deletePost:'删除帖子', deleteConfirm:'您确定吗？', approve:'批准', reject:'拒绝' },
      donations: { title:'支持ラーメンアニメ', subtitle:'帮助社区成长', desc:'您的支持有助于保持服务器运行和开发新功能。', payWithPayPal:'通过PayPal捐赠', sendViaRevolut:'通过Revolut发送', copyLink:'复制Revolut链接', copied:'已复制！', recentDonors:'最近支持者', anonymous:'匿名', thankYou:'感谢您的支持！', goal:'目标', raised:'已筹', totalDonations:'总筹款', donorCount:'支持者', noDonations:'成为第一个支持者！' },
      listing: { back:'返回', buy_now:'立即购买', place_bid:'出价', current_bid:'当前出价', time_left:'剩余时间', instant_buy:'立即购买', condition:'状况', seller:'卖家', shipping:'运费', ask_question:'提问', add_watchlist:'添加到关注', share:'分享', bid_history:'出价历史', recent_bids:'最近出价', make_offer:'出价', verified_seller:'认证卖家', description:'描述', similar_items:'相似商品', auction_ended:'拍卖结束', quantity:'数量', your_bid:'您的出价', min_bid:'最低出价', checkout:'结账', no_bids:'暂无出价，成为第一个！', auction:'拍卖', fixed:'固定价格', loading:'加载中...', not_found:'找不到商品', ends_in:'结束于', buy_price:'购买价格', bid_now:'立即出价', contacting:'联系中...', contact_seller:'联系卖家', watchlisted:'已关注', watch:'关注', unwatch:'取消关注' },
      messages: { title:'消息', login_required:'需要登录', login_to_view:'请登录以查看消息', no_messages:'暂无消息', type_message:'输入消息...', send:'发送', conversation:'对话', new_message:'新消息', coming_soon:'完整消息功能即将推出。' },
      orders: { title:'订单', my_purchases:'我的购买', my_sales:'我的销售', no_purchases:'暂无购买记录', no_sales:'暂无销售记录', order_number:'订单号', status:'状态', total:'总计', items:'商品', track:'追踪', view_details:'查看详情', pending:'待处理', paid:'已付款', shipped:'已发货', delivered:'已送达', cancelled:'已取消', refunded:'已退款', placed_on:'下单时间', buyer:'买家', seller:'卖家', loading:'加载中...', login_required:'请登录以查看订单' },
      createListing: { title:'创建商品', subtitle:'出售您的动漫商品', item_title:'标题', item_title_ph:'例：火影忍者仙人模式手办', description:'描述', description_ph:'详细描述您的商品...', price:'价格（美元）', condition:'状况', category:'类别', images:'图片', listing_type:'商品类型', auction:'拍卖', fixed_price:'固定价格', duration:'时长', duration_7:'7天', duration_14:'14天', duration_30:'30天', submit:'发布', creating:'发布中...', success:'商品已发布！', error:'发布失败', add_images:'添加图片', max_images:'最多10张', ai_suggest:'AI建议', ai_analyzing:'分析中...', preview:'预览', new:'全新', like_new:'近全新', used:'二手', cat_figures:'动漫手办', cat_manga:'漫画/书籍', cat_art:'艺术/原画', cat_collectibles:'收藏品', cat_gaming:'游戏', cat_cards:'卡牌', cat_apparel:'服装', cat_accessories:'配件', cat_3d:'3D打印', cat_other:'其他', login_required:'请登录以创建商品', min_images:'请至少添加一张图片', min_price:'价格至少为$0.01', title_required:'标题为必填项' },
      friends: { title:'好友', my_friends:'我的好友', pending_requests:'待处理请求', no_friends:'暂无好友', no_requests:'暂无待处理请求', accept:'接受', decline:'拒绝', remove:'删除', message:'消息', friend_since:'好友关系建立于', mutual:'共同好友', online:'在线', offline:'离线', loading:'加载中...', view_profile:'查看档案', request_sent:'请求已发送', add_friend:'添加好友', remove_friend:'删除好友', confirm_remove:'删除此好友？' },
      orderDetail: { back:'返回订单', order_summary:'订单摘要', order_status:'订单状态', pending:'等待付款', payment_received:'已收款', shipped:'已发货', delivered:'已送达', cancelled:'已取消', items_ordered:'订购商品', seller_info:'卖家', buyer_info:'买家', shipping_address:'收货地址', payment_method:'付款方式', contact_seller:'联系卖家', contact_buyer:'联系买家', open_dispute:'提起争议', submit_review:'撰写评价', track_package:'追踪包裹', total:'总计', subtotal:'小计', shipping_cost:'运费', loading:'加载中...', not_found:'找不到订单', mark_shipped:'标记为已发货', confirm_delivery:'确认收货', order_number:'订单', placed:'下单于', quantity:'数量' },
      geoBlock: { title:'服务不可用', subtitle:'此服务在您所在地区不可用。', detected:'检测到：', retry:'重新检测', select_country:'手动选择国家', not_available:'我们尚未在您的地区提供服务。', checking:'正在检查您的位置...', available_in:'可用国家' },
    }},
  };

  resources.en.translation = deepMerge(resources.en.translation, extendedEn);
  resources.en.translation = deepMerge(resources.en.translation, legalEn);

  const LEGAL_LOCALE_BUNDLES: Record<string, typeof legalEn> = {
    ja: legalJa,
    ko: legalKo,
    de: legalDe,
    es: legalEs,
    fr: legalFr,
    'zh-CN': legalZh,
  };

  for (const [lng, legalBundle] of Object.entries(LEGAL_LOCALE_BUNDLES)) {
    if (!resources[lng]) continue;
    resources[lng].translation = deepMerge(resources[lng].translation, extendedEn);
    resources[lng].translation = deepMerge(resources[lng].translation, legalBundle);
    const tokushoho = tokushohoByLocale[lng];
    if (tokushoho) {
      resources[lng].translation = deepMerge(resources[lng].translation, { tokushoho });
    }
  }

  if (resources.ja) {
    resources.ja.translation = deepMerge(resources.ja.translation, kyotoJaOverrides);
  }

  const { legalPrivacy: _legalPrivacy, legalTerms: _legalTerms, ...enTranslationWithoutLegal } =
    resources.en.translation;

  // All remaining languages use English as fallback - add abbreviated translations for each
  const makeSimple = (nav: Record<string,string>, hero_sub: string, signin: string, join: string) => ({
    ...enTranslationWithoutLegal,
    nav: { ...resources.en.translation.nav, ...nav },
    hero: { ...resources.en.translation.hero, subtitle: hero_sub },
    login: {
      ...resources.en.translation.login,
      welcomeBack: signin,
      signInDesc: signin,
      joinDesc: join,
      welcomeToast: `${signin}!`,
      registerToast: `${join}!`,
    },
  });

  const extraLangs: Record<string, any> = {
    'zh-TW': { translation: { ...resources['zh-CN'].translation, hero: { ...resources['zh-CN'].translation.hero, subtitle: '您一站式的動漫3D列印商品和卡牌收藏店。用心製作，用心發貨。' }, nav: { ...resources['zh-CN'].translation.nav, prints3d:'3D列印', myProfile:'我的檔案' } } },
    hi: { translation: { ...makeSimple({ home:'होम', brand:'Ramen Anime', shop:'दुकान', prints3d:'3D प्रिंट', cards:'कार्ड', contact:'संपर्क', social:'फोरम', login:'लॉगिन', terms:'नियम', friends:'मित्र', profile:'प्रोफाइल', marketplace:'बाज़ार', myProfile:'मेरी प्रोफाइल', admin:'एडमिन', logout:'लॉगआउट', menu:'मेनू', language:'भाषा', donate:'दान' }, 'कस्टम 3D प्रिंटेड एनिमे गुड्स और ट्रेडिंग कार्ड्स की आपकी एकमात्र दुकान।', 'वापसी पर स्वागत है', 'खाता बनाएं') } },
    id: { translation: { ...makeSimple({ home:'Beranda', brand:'Ramen Anime', shop:'Toko', prints3d:'Cetak 3D', cards:'Kartu', contact:'Kontak', social:'Forum', login:'Masuk', terms:'Syarat', friends:'Teman', profile:'Profil', marketplace:'Pasar', myProfile:'Profil Saya', admin:'Admin', logout:'Keluar', menu:'Menu', language:'Bahasa', donate:'Donasi' }, 'Toko serba ada untuk barang anime cetak 3D dan kartu koleksi.', 'Selamat datang kembali', 'Buat akun') } },
    ms: { translation: { ...makeSimple({ home:'Utama', brand:'Ramen Anime', shop:'Kedai', prints3d:'Cetak 3D', cards:'Kad', contact:'Hubungi', social:'Forum', login:'Log Masuk', terms:'Terma', friends:'Rakan', profile:'Profil', marketplace:'Pasaran', myProfile:'Profil Saya', admin:'Admin', logout:'Log Keluar', menu:'Menu', language:'Bahasa', donate:'Derma' }, 'Kedai serba lengkap untuk barangan anime cetak 3D dan kad koleksi.', 'Selamat kembali', 'Buat akaun') } },
    tl: { translation: { ...makeSimple({ home:'Tahanan', brand:'Ramen Anime', shop:'Tindahan', prints3d:'3D Print', cards:'Kard', contact:'Makipag-ugnayan', social:'Forum', login:'Mag-login', terms:'Mga Tuntunin', friends:'Mga Kaibigan', profile:'Profile', marketplace:'Palengke', myProfile:'Aking Profile', admin:'Admin', logout:'Mag-logout', menu:'Menu', language:'Wika', donate:'Mag-donate' }, 'Ang iyong one-stop shop para sa custom anime goods at trading cards.', 'Maligayang pagbabalik', 'Lumikha ng account') } },
    vi: { translation: { ...makeSimple({ home:'Trang chủ', brand:'Ramen Anime', shop:'Cửa hàng', prints3d:'In 3D', cards:'Thẻ bài', contact:'Liên hệ', social:'Diễn đàn', login:'Đăng nhập', terms:'Điều khoản', friends:'Bạn bè', profile:'Hồ sơ', marketplace:'Chợ', myProfile:'Hồ sơ của tôi', admin:'Quản trị', logout:'Đăng xuất', menu:'Menu', language:'Ngôn ngữ', donate:'Ủng hộ' }, 'Cửa hàng một cửa cho đồ anime in 3D và thẻ bài sưu tập.', 'Chào mừng trở lại', 'Tạo tài khoản') } },
    th: { translation: { ...makeSimple({ home:'หน้าแรก', brand:'Ramen Anime', shop:'ร้านค้า', prints3d:'พิมพ์ 3D', cards:'การ์ด', contact:'ติดต่อ', social:'ฟอรัม', login:'เข้าสู่ระบบ', terms:'เงื่อนไข', friends:'เพื่อน', profile:'โปรไฟล์', marketplace:'ตลาด', myProfile:'โปรไฟล์ของฉัน', admin:'ผู้ดูแล', logout:'ออกจากระบบ', menu:'เมนู', language:'ภาษา', donate:'บริจาค' }, 'ร้านครบวงจรสำหรับสินค้าอนิเมะพิมพ์ 3D และการ์ดสะสม', 'ยินดีต้อนรับกลับ', 'สร้างบัญชี') } },
    ar: { translation: { ...makeSimple({ home:'الرئيسية', brand:'Ramen Anime', shop:'المتجر', prints3d:'طباعة ثلاثية الأبعاد', cards:'بطاقات', contact:'اتصل بنا', social:'المنتدى', login:'تسجيل الدخول', terms:'الشروط', friends:'الأصدقاء', profile:'الملف الشخصي', marketplace:'السوق', myProfile:'ملفي الشخصي', admin:'المشرف', logout:'تسجيل الخروج', menu:'القائمة', language:'اللغة', donate:'تبرع' }, 'متجرك الشامل للبضائع الأنيمي المطبوعة ثلاثية الأبعاد وبطاقات التداول.', 'مرحباً بعودتك', 'إنشاء حساب') } },
    he: { translation: { ...makeSimple({ home:'דף הבית', brand:'Ramen Anime', shop:'חנות', prints3d:'הדפסת תלת-מימד', cards:'קלפים', contact:'צור קשר', social:'פורום', login:'התחברות', terms:'תנאים', friends:'חברים', profile:'פרופיל', marketplace:'שוק', myProfile:'הפרופיל שלי', admin:'מנהל', logout:'התנתקות', menu:'תפריט', language:'שפה', donate:'תרומה' }, 'חנות one-stop לדמויות אנימה מודפסות ב-3D וקלפי אספנות.', 'ברוך שובך', 'צור חשבון') } },
    tr: { translation: { ...makeSimple({ home:'Ana Sayfa', brand:'Ramen Anime', shop:'Mağaza', prints3d:'3D Baskı', cards:'Kartlar', contact:'İletişim', social:'Forum', login:'Giriş', terms:'Şartlar', friends:'Arkadaşlar', profile:'Profil', marketplace:'Pazar', myProfile:'Profilim', admin:'Yönetici', logout:'Çıkış', menu:'Menü', language:'Dil', donate:'Bağış' }, 'Özel 3D baskılı anime ürünleri ve koleksiyon kartları için tek durak mağazanız.', 'Tekrar hoş geldiniz', 'Hesap oluştur') } },
    it: { translation: { ...makeSimple({ home:'Home', brand:'Ramen Anime', shop:'Negozio', prints3d:'Stampe 3D', cards:'Carte', contact:'Contatti', social:'Forum', login:'Accedi', terms:'Termini', friends:'Amici', profile:'Profilo', marketplace:'Mercato', myProfile:'Il mio profilo', admin:'Admin', logout:'Esci', menu:'Menu', language:'Lingua', donate:'Donare' }, 'Il tuo negozio per articoli anime stampati in 3D e carte collezionabili.', 'Bentornato', 'Crea account') } },
    nl: { translation: { ...makeSimple({ home:'Home', brand:'Ramen Anime', shop:'Winkel', prints3d:'3D-prints', cards:'Kaarten', contact:'Contact', social:'Forum', login:'Inloggen', terms:'Voorwaarden', friends:'Vrienden', profile:'Profiel', marketplace:'Markt', myProfile:'Mijn profiel', admin:'Admin', logout:'Uitloggen', menu:'Menu', language:'Taal', donate:'Doneren' }, 'Uw one-stop-shop voor op maat gemaakte 3D-geprinte anime-artikelen en verzamelkaarten.', 'Welkom terug', 'Account aanmaken') } },
    pt: { translation: { ...makeSimple({ home:'Início', brand:'Ramen Anime', shop:'Loja', prints3d:'Impressões 3D', cards:'Cartas', contact:'Contato', social:'Fórum', login:'Entrar', terms:'Termos', friends:'Amigos', profile:'Perfil', marketplace:'Mercado', myProfile:'Meu Perfil', admin:'Admin', logout:'Sair', menu:'Menu', language:'Idioma', donate:'Doar' }, 'Sua loja completa para artigos anime impressos em 3D e cartas colecionáveis.', 'Bem-vindo de volta', 'Criar conta') } },
    pl: { translation: { ...makeSimple({ home:'Strona główna', brand:'Ramen Anime', shop:'Sklep', prints3d:'Druki 3D', cards:'Karty', contact:'Kontakt', social:'Forum', login:'Zaloguj', terms:'Warunki', friends:'Znajomi', profile:'Profil', marketplace:'Rynek', myProfile:'Mój profil', admin:'Admin', logout:'Wyloguj', menu:'Menu', language:'Język', donate:'Wspomóż' }, 'Twój sklep z niestandardowymi drukowanymi 3D artykułami anime i kartami kolekcjonerskimi.', 'Witamy ponownie', 'Utwórz konto') } },
    ro: { translation: { ...makeSimple({ home:'Acasă', brand:'Ramen Anime', shop:'Magazin', prints3d:'Imprimare 3D', cards:'Cărți', contact:'Contact', social:'Forum', login:'Autentificare', terms:'Termeni', friends:'Prieteni', profile:'Profil', marketplace:'Piață', myProfile:'Profilul meu', admin:'Admin', logout:'Deconectare', menu:'Meniu', language:'Limbă', donate:'Donează' }, 'Magazinul tău complet pentru articole anime imprimate 3D și cărți de colecție.', 'Bine ai revenit', 'Creează cont') } },
    el: { translation: { ...makeSimple({ home:'Αρχική', brand:'Ramen Anime', shop:'Κατάστημα', prints3d:'3D Εκτυπώσεις', cards:'Κάρτες', contact:'Επικοινωνία', social:'Φόρουμ', login:'Σύνδεση', terms:'Όροι', friends:'Φίλοι', profile:'Προφίλ', marketplace:'Αγορά', myProfile:'Το προφίλ μου', admin:'Admin', logout:'Αποσύνδεση', menu:'Μενού', language:'Γλώσσα', donate:'Δωρεά' }, 'Το ολοκληρωμένο κατάστημα για εξατομικευμένα προϊόντα anime και συλλεκτικές κάρτες.', 'Καλώς ήρθατε πίσω', 'Δημιουργία λογαριασμού') } },
    sv: { translation: { ...makeSimple({ home:'Hem', brand:'Ramen Anime', shop:'Butik', prints3d:'3D-tryck', cards:'Kort', contact:'Kontakt', social:'Forum', login:'Logga in', terms:'Villkor', friends:'Vänner', profile:'Profil', marketplace:'Marknad', myProfile:'Min profil', admin:'Admin', logout:'Logga ut', menu:'Meny', language:'Språk', donate:'Donera' }, 'Din allt-i-ett-butik för anpassade 3D-tryckta anime-varor och samlingskort.', 'Välkommen tillbaka', 'Skapa konto') } },
    cs: { translation: { ...makeSimple({ home:'Domů', brand:'Ramen Anime', shop:'Obchod', prints3d:'3D tisky', cards:'Karty', contact:'Kontakt', social:'Fórum', login:'Přihlásit', terms:'Podmínky', friends:'Přátelé', profile:'Profil', marketplace:'Tržiště', myProfile:'Můj profil', admin:'Admin', logout:'Odhlásit', menu:'Menu', language:'Jazyk', donate:'Přispět' }, 'Váš all-in-one obchod s vlastními 3D tisknutými anime předměty a sběratelskými kartami.', 'Vítejte zpět', 'Vytvořit účet') } },
    hu: { translation: { ...makeSimple({ home:'Főoldal', brand:'Ramen Anime', shop:'Bolt', prints3d:'3D nyomtatás', cards:'Kártyák', contact:'Kapcsolat', social:'Fórum', login:'Bejelentkezés', terms:'Feltételek', friends:'Barátok', profile:'Profil', marketplace:'Piac', myProfile:'Profilom', admin:'Admin', logout:'Kijelentkezés', menu:'Menü', language:'Nyelv', donate:'Adományozás' }, 'Mindent egy helyen az egyedi 3D nyomtatott anime árukért és gyűjtőkártyákért.', 'Üdvözöljük újra', 'Fiók létrehozása') } },
    bg: { translation: { ...makeSimple({ home:'Начало', brand:'Ramen Anime', shop:'Магазин', prints3d:'3D печат', cards:'Карти', contact:'Контакт', social:'Форум', login:'Вход', terms:'Условия', friends:'Приятели', profile:'Профил', marketplace:'Пазар', myProfile:'Моят профил', admin:'Админ', logout:'Изход', menu:'Меню', language:'Език', donate:'Дарение' }, 'Вашият универсален магазин за персонализирани 3D аниме стоки и колекционерски карти.', 'Добре дошли отново', 'Създай акаунт') } },
    da: { translation: { ...makeSimple({ home:'Hjem', brand:'Ramen Anime', shop:'Butik', prints3d:'3D-print', cards:'Kort', contact:'Kontakt', social:'Forum', login:'Log ind', terms:'Vilkår', friends:'Venner', profile:'Profil', marketplace:'Marked', myProfile:'Min profil', admin:'Admin', logout:'Log ud', menu:'Menu', language:'Sprog', donate:'Donér' }, 'Din alt-i-en butik for brugerdefinerede 3D-printede anime-varer og samlerkort.', 'Velkommen tilbage', 'Opret konto') } },
    fi: { translation: { ...makeSimple({ home:'Etusivu', brand:'Ramen Anime', shop:'Kauppa', prints3d:'3D-tulosteet', cards:'Kortit', contact:'Yhteystiedot', social:'Foorumi', login:'Kirjaudu', terms:'Ehdot', friends:'Ystävät', profile:'Profiili', marketplace:'Markkinapaikka', myProfile:'Oma profiili', admin:'Admin', logout:'Kirjaudu ulos', menu:'Valikko', language:'Kieli', donate:'Lahjoita' }, 'Kertaostospaikkasi mukautetuille 3D-tulostetuille anime-tavaroille ja keräilykorteille.', 'Tervetuloa takaisin', 'Luo tili') } },
  };

  Object.assign(resources, extraLangs);

  i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources,
      fallbackLng: 'en',
      supportedLngs: Object.keys(resources),
      nonExplicitSupportedLngs: true,
      interpolation: { escapeValue: false },
      returnEmptyString: false,
      detection: {
        order: ['localStorage', 'navigator'],
        caches: ['localStorage'],
        lookupLocalStorage: 'ramen_anime_lang',
      },
    });

i18n.on('languageChanged', setDocumentDirection);
setDocumentDirection(i18n.language);

export default i18n;
  